### ISSUE TITLE
`assert` appears to make Yices hang indefinitely

### ISSUE THREAD

**Issue by robdockins** [SRI-CSL/yices2#101]
The attached file causes yices to enter a state where it consumes 100% CPU for an apparently unlimited amount of time (at least 10 minutes), and will not respond to keyboard interrupts.  This is odd because no query is issued to the solver, just a sequence of definitions and asserts.

[yices.txt](https://github.com/SRI-CSL/yices2/files/2527027/yices.txt)

This example has been minimized from a larger example, and has proved resistant to any further minimization.  Removing any one of the remaining assert statements causes the file to be processed without incident.

Note, this is with master `yices`, revision a221a3604af51c4333cd1c2682511a3213cbb516

**Comment by BrunoDutertre** [comment]
Infinite loop fixed in 8216180e8b1ab1d19bad5897a4fd1d4201cde133.

**Comment by robdockins** [comment]
Thanks @BrunoDutertre!
