### ISSUE TITLE
Possible error in smt pop

### ISSUE THREAD

**Issue by aman-goel** [SRI-CSL/yices2#102]
Hi,

I think there could be a possible subtle bug in how pop is done in smt core due to interaction with interrupts in interactive mode. When an interrupt occurs during a call to `yices_check_context()`, there can be lemmas queued to be added. The following `smt_pop()` call corresponding to the interrupt never clears the queued lemmas. Does the modification suggested in commit [here](https://github.com/aman-goel/yices2/commit/de9501d2846bc04fb65542d42b2d7d5bc0e5ef20) makes sense?

I encountered this issue due to a Yices internal assertion failure getting triggered (literal going out of bounds) after a long sequence of interactive queries using Yices C API (when using Yices 2 master head for model checking in a tool called [avr](https://github.com/aman-goel/avr)). It is hard to replicate this issue especially using a SMT2 file as it seem to occur very rarely, and only when making incremental queries with timeouts.

It would be great to have a review of the code relating to SMT pop to make sure it handles interaction with interrupts correctly.

Please correct me if I am thinking incorrectly, and let me know if any detail is required from my side.
Thanks.

--
Aman

**Comment by BrunoDutertre** [comment]
Hi Aman,

Yes, this looks like a good fix to a real bug. Thanks.
I'll incorporate your change.

Bruno
