### ISSUE TITLE
Wrong result for QF_LRA problem when using the C API and using yices_default_config_for_logic

### ISSUE THREAD

**Issue by mikand** [SRI-CSL/yices2#104]
(This bug first manifested by using pysmt, see https://github.com/pysmt/pysmt/issues/547)

With [this](https://github.com/SRI-CSL/yices2/files/2703157/bug.zip) minimal C program that uses the C API, yices 2.6.0 reports an SMT problem to be UNSAT when the configuration  is initialized with `yices_default_config_for_logic(yices_config, "QF_LRA")`; instead, when the empty configuration is used, the problem is recognized as SAT (that is the correct answer according to Z3, MathSAT and CVC4).

The attached program highlights the problem, if no paramteres are specified on the command line, the code does not invoke  `yices_default_config_for_logic(yices_config, "QF_LRA")` and yices correctly reports SAT, if anything is specified on the command line, the inocation is executed and yices returns UNSAT.

Using yices from the comand-line, the SMT2 file [test1211.smt2.gz](https://github.com/SRI-CSL/yices2/files/2703175/test1211.smt2.gz) that corresponds to the problem above is correctly recognized as SAT.

**Comment by BrunoDutertre** [comment]
Thanks for reporting this. It's fixed now.
