### ISSUE TITLE
Potentially NULL pointer dereference in node_occ_t bvc_dag_nocc_of_var

### ISSUE THREAD

**Issue by shaobo-he** [SRI-CSL/yices2#106]
Function `node_occ_t bvc_dag_nocc_of_var` calls `int_hmap_find` to get the element, which may not in the hash, leading to a NULL pointer dereference. I doubt the assertion preceding the call to `int_hmap_find` prevents such case from happening.

**Comment by dddejan** [comment]
The ``vset`` and ``vmap`` fields of ``bvc_dag_t`` are kept in sync, so the assertion does prevent it from happening. 

https://github.com/SRI-CSL/yices2/blob/1d108a0f910bfe040ef347e92743f377c209fea5/src/solvers/bv/bvpoly_dag.c#L1462

**Comment by shaobo-he** [comment]
This is very helpful. Thank you @dddejan
