### ISSUE TITLE
Potential NULL pointer dereference in dsolver_reduce_columns

### ISSUE THREAD

**Issue by shaobo-he** [SRI-CSL/yices2#107]
Function `dsolver_process_row` calls `dsolver_reduce_columns` which may leave `&solver->active_columns` an empty heap pointer. If so, `ptr_heap_get_min` in `dsolver_reduce_columns` may return a NULL pointer.

The error trace returned by corral is attached.
[Bug4.txt](https://github.com/SRI-CSL/yices2/files/2862531/Bug4.txt)

**Comment by BrunoDutertre** [comment]
`dsolver_reduce_columns` is called only from `dsolver_process_row` and never with an 
empty heap pointer. So when `dsolver_reduce_columns` is called, `&solver->active_columns`
can't be empty.

Implicitly, the code works on a matrix _M[i, j]_. Given a row _r_, `desolver_process_row` collects
all the indices _j_  such that _M[r, j]_ is non-zero. These indices define a set of columns _C_ that are
processed in `dsolver_reduce_columns`. The heap `solver->active_columns` stores the set _C_. 

In the code, row r is represented as an integer bag `row` that contains the indices _j_
such that _M[r, j] /= 0_. `ibag_nelems(row)` is the number of these elements.
 `dsolver_process_row` doesn't call `dsolver_reduce_columns` if `ibag_nelems(row) = 0`.
