### ISSUE TITLE
Potential NULL pointer dereference in try_lower_bound_propagation

### ISSUE THREAD

**Issue by shaobo-he** [SRI-CSL/yices2#109]
In function ` try_lower_bound_propagation` (file solvers/simplex/simplex_propagator1.h), `c` is initialized to `NULL` but may not be updated in the `do while` loop (e.g., `x` != `y`), resulting in a NULL pointer dereference in `xq_div`.

The error trace is attached.
[Bug13.txt](https://github.com/SRI-CSL/yices2/files/2866606/Bug13.txt)

**Comment by dddejan** [comment]
```c
rational_t *c; // coefficient of y in p
```
The variable `y` is guaranteed to exist in row `p`. When loop is done, `c` will be inititalized.
