### ISSUE TITLE
Possible bug in model generation with arrays

### ISSUE THREAD

**Issue by aman-goel** [SRI-CSL/yices2#112]
Hi,

I would like to report a possible bug in Yices model generation when arrays are involved. The model produced does not satisfy all the assertions given to the solver. The simplest case where I encountered this is with multiple calls to check-sat (even without any push/pop), with logic set as "ALL". Please find attached a SMT2 file (yices_model_bug.smt2) to reproduce the bug. The last call to check-sat produces SAT, with an incorrect model which assigns the definition `.2436` as false, even when the assertion `(assert .2436)` is already asserted. 

Version info (current master):
```
Yices 2.6.1
Copyright SRI International.
Linked with GMP 6.1.2
Copyright Free Software Foundation, Inc.
Build date: 2019-02-25
Platform: x86_64-pc-linux-gnu (release)
```

Snapshot of the error:
```
; check yices_model_bug.smt2 for complete problem trace
(set-logic ALL)

; subset of of declarations, definitions and assertions
(declare-fun m$transfer$next_ufbv () (Array Int (Array Int (_ BitVec 1))))
(declare-fun m$856_ufbv () Bool)
(declare-fun m$v$176$next_ufbv () (Array Int (Array Int (_ BitVec 1))))

(define-fun .407 () (Array Int (Array Int (_ BitVec 1))) m$transfer$next_ufbv)
(define-fun .2423 () Bool m$856_ufbv)
(define-fun .2424 () (Array Int (Array Int (_ BitVec 1))) m$v$176$next_ufbv)
(define-fun .2435 () Bool (= .407 .2424))
(define-fun .2436 () Bool (= .2423 .2435))

(assert .2436)

; many more stuff hidden (no push/pop commands)

(check-sat)
; gives SAT
(get-value (m$transfer$next_ufbv))
(get-value (m$v$176$next_ufbv))
(get-value (.407))
(get-value (.2423))
(get-value (.2424))
(get-value (.2435))
(get-value (.2436))

; output
; ((m$transfer$next_ufbv @fun_62))
; ((m$v$176$next_ufbv @fun_62))
; ((.407 @fun_62))
; ((.2423 false))
; ((.2424 @fun_62))
; ((.2435 true))
; ((.2436 false))
```

I am expecting this issue to be a bug in Yices array model generation due to elimination of local variables.

I encountered this issue using a tool called [Averroes 2](https://github.com/aman-goel/avr) (a word-level model checker) which uses Yices for incremental SMT solving via C API. Unfortunately, it was not easy to extract a smaller, even simpler case with the issue.

Please let me know of any detail required from my side.
Thank you.

[yices_model_bug.smt2.txt](https://github.com/SRI-CSL/yices2/files/2901578/yices_model_bug.smt2.txt)

Regards
Aman

**Comment by aman-goel** [comment]
Attaching a simpler version of the problem (no bitvectors and shorter trace) with the same issue.

[yices_model_bug_bool.smt2.txt](https://github.com/SRI-CSL/yices2/files/2901633/yices_model_bug_bool.smt2.txt)

**Comment by BrunoDutertre** [comment]
Thanks for reporting this. I'll look into it.

Bruno

**Comment by BrunoDutertre** [comment]
@aman-goel, this should work now in master. Apologies for the delay.

Bruno

**Comment by aman-goel** [comment]
@BrunoDutertre  Thanks a lot for the updates.
