### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [SRI-CSL/yices2#114]
I would like to point out that an identifier like “[`__YICES_VERSION`](https://github.com/SRI-CSL/yices2/blob/97fe0ba473ec5ae2a08f9604afc00fc20fcc2dcb/src/include/yices.h#L84 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by BrunoDutertre** [comment]
Low priority but we'll look into it maybe. Thanks for pointing this out.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
