### ISSUE TITLE
Output "Decimal" Bitvectors

### ISSUE THREAD

**Issue by arjunvish** [SRI-CSL/yices2#135]
Yices2 seems to accept bitvector constants with decimal numerals as described in the SMTLib extension for bitvectors (under extensions in http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_BV).
- Bitvector Constants:
    (_ bvX n) where X and n are numerals, i.e. (_ bv13 32),
    abbreviates the term #bY of sort (_ BitVec n) such that
    [[#bY]] = nat2bv[n](X) for X=0, ..., 2^n - 1.

However, it seems to output bitvectors as binary literals ("#b" followed by bits) by default. Could you add an option to output these "decimal" bitvectors?

**Comment by BrunoDutertre** [comment]
Done
