### ISSUE TITLE
Support for `define-fun` ?

### ISSUE THREAD

**Issue by simsong** [SRI-CSL/yices2#152]
This single-line SMT file generates an error.

Here is the file:

    (define-fun Male () Bool true)

```
% ~/yices-2.6.1/bin/yices --logic=QF_UFLIA oneline.smt
oneline.smt: syntax error: (line 1, column 2): define-fun is not a command
%
```

Does Yices not support `define-fun` ?

**Comment by ianamason** [comment]
There are three front ends supplied by yices. You are using the one for the yices language, not the smt language.  Yices has very good documentation. I suggest you use it. There are also lots and lots of examples in the tests, just pay attention to the file suffix.

**Comment by simsong** [comment]
Thank you for your email. I found your online documentation to be excellent for the library, but I cannot find documentation for the command line program, nor for the “front ends” that you reference. The “docs” tab goes to https://yices.csl.sri.com/yices2-documentation.html which does not mention front ends or the command line. Any help that you can provide would be very much appreciated.

**Comment by ianamason** [comment]
Take a look at the manual. Chapter 5.

**Comment by ianamason** [comment]
Plus the very first example in the README  uses `yices-smt2`

**Comment by simsong** [comment]
Thanks! I did not see the manual from the website link, but I have it now.
It seems that we will need to modify our program to output a slightly
different SMT format for yices2, but we are happy to do that. I'll let you
know if we have further problems.

**Comment by ianamason** [comment]
If you have a tool that is using yices as a backend solver, you should take a look at the API.
