### ISSUE TITLE
get-model and get-value produce invalid output for non-rational values

### ISSUE THREAD

**Issue by yaqwsx** [SRI-CSL/yices2#156]
Consider the following SMTLIB2:
```
(set-logic QF_NRA )

(declare-fun x () Real)
(declare-fun y () Real)
(assert (= (* x x) 2))
(assert (= (* y y) 4))
(check-sat)
(get-model)
(get-value (x))
(get-value (y))
(exit)
```

calling `yieces-smt2` produces the following output:

```
sat
(= x ???)
(= y (- 2))
((x 0))
((y (- 2)))
```

It seems that "???" is printed for non-rational values. I would expect the solver to output a symbolic representation or a decimal approximation. Also the get-value prints 0, which is clearly incorrect.

**Comment by BrunoDutertre** [comment]
I can't reproduce this. When I  run yices-smt2 on your example, I get this:
```
sat
(= x -1.414214)
(= y (- 2))
((x -1.414214))
((y (- 2)))
```

Can you give more details? Which version are you running.

**Comment by yaqwsx** [comment]
The issue was related to the latest release (ba13d37) - when I compile the upstream version from the repository, it behaves as expected.
