### ISSUE TITLE
QF_UFBV suspiciously fast

### ISSUE THREAD

**Issue by aep** [SRI-CSL/yices2#161]
Hi

i have around half a million lines of smt2 in the [zz compiler](https://github.com/aep/zz)  self test suite.

boolector outperforms z3 by some margin, but yices2 is **10 times** faster. 
this is inconsistent with the smt-comp where boolector outperforms yices2.

attached is an excerpt of the smt

[smt.zip](https://github.com/SRI-CSL/yices2/files/4014488/smt.zip)

i'll do some deeper testing, but maybe someone can already see what's wrong

**Comment by BrunoDutertre** [comment]
Yices won QF_UFBV in SMTCOMP 2019. It was more than 10 times faster than
Boolector on satisfiable instances (https://smt-comp.github.io/2019/results/qf-ufbv-single-query).

**Comment by aep** [comment]
wow that's really impressive. congratulations!
i poked around a little and couldn't find any immediate problems, so closing this.

currently working on switching to cvc4 which has similar performance but a less problematic license.
