### ISSUE TITLE
Answers for `get-model` does not respect SMT-LIB 2 standard

### ISSUE THREAD

**Issue by AdrienChampion** [SRI-CSL/yices2#162]
When asked for a model, yices 2 (2.6.1) produces definitions as

```lisp
(
    (= <ident> <value>)
    ...
)
```

But according to [SMT-LIB 2.6](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf) (page 47), models should look function symbol definitions, *i.e.*

```lisp
(
    (define-fun <ident> ( <args_list> ) <sort> <value>)
    ...
)
```

Is this on purpose? Do you plan to produce models SMT-LIB-style in the future?

I am asking this as I am adding support for Yices 2 in the Rust SMT-LIB 2 crate [rsmt2](https://crates.io/crates/rsmt2), where this discrepancy causes (relatively minor) problems.

**Comment by BrunoDutertre** [comment]
Get the latest version from gitub then try command-line option ``--smt2-model-format``.

**Comment by BrunoDutertre** [comment]
And yes. It is on purpose. The yices format is much simpler, more compact,
less verbose, and easier to parse. The yices format also predates the 2.6 standard.

**Comment by AdrienChampion** [comment]
I see, thank you :)

I'm curious how you print models for non-nullary function symbols though, do you use some kind of closure notation?

In any case, let me go ahead and close this.

**Comment by BrunoDutertre** [comment]
That's documented in the Yices manual: https://yices.csl.sri.com/papers/manual.pdf
