### ISSUE TITLE
Bug in mcsat

### ISSUE THREAD

**Issue by BrunoDutertre** [SRI-CSL/yices2#164]
Something is wrong in the latest yices master that causes seg-faults in Sally.
When building Sally with the latest Yices2,

make check fails on `` sally/test/regress/bv/test_01.mcmt``

In debug mode, we get a assertion failure in the mcsat code:

```
./src/sally /Users/bruno/Repos/sally/test/regress/bv/test_01.mcmt --engine bmc
Assertion failed: (level >= trail->decision_level_base), function trail_add_propagation, file mcsat/trail.c, line 197.
Abort
```

**Comment by dddejan** [comment]
Sally runs DPLL(T) and MCSAT so the bitvectors seem to not be good with incremental solving. It should do so only if DPLL doesn't support the theory. Will take a look as soon as the flu lets go.

**Comment by dddejan** [comment]
Should be fixed. I restarted the Sally build and will close if it passes.

**Comment by BrunoDutertre** [comment]
Works for me. Thanks.
