### ISSUE TITLE
Yices unresponsive after (pop)

### ISSUE THREAD

**Issue by robdockins** [SRI-CSL/yices2#168]
I've managed to drive yices into an unresponsive state where it is running 100% CPU and doesn't respond to SIGINT (it does, however, respond to SIGTERM).  The following file demonstrates the issue (warning, 10M big).  I'm not sure how to go about minimizing it.  Oddly, the last command issued to yices is a `(pop)`, which doesn't make a lot of sense. I'm using the 2.6.1 release version of yices for OSX.

https://gist.githubusercontent.com/robdockins/b8570f6fe374d3492136e7b114ff45cc/raw/5a516c29465ccefdf83bd0dae1d39e1a05e02a00/yices.out

**Comment by robdockins** [comment]
The symptoms of this are similar to #101... I suppose it might be the same cause actually.  I thought there had been a release since then, but perhaps I'm mistaken.

**Comment by BrunoDutertre** [comment]
Yes, that's the same bug. It's fixed in master.
Another argument for a new release.
