### ISSUE TITLE
setting a timeout via the C API

### ISSUE THREAD

**Issue by ffrohn** [SRI-CSL/yices2#171]
I am looking for a way to set a timeout (such that yices_check_context gives up when the timeout expires) using the C API, but I can't figure it out. Can you tell me how to do it?

Similarly, I would like to disable model-building (hoping that this will speed up Yices). Is that possible via the C API?

Thank you very much for your help!

**Comment by ianamason** [comment]
You would use a timer, which when ran out, called 
```
void yices_stop_search(context_t* ctx)
```
on the context that is being checked.  My guess is you would handle a signal like `SIGALRM`
rather than use multiple threads.

**Comment by ffrohn** [comment]
Thanks!

**Comment by ianamason** [comment]
Now that I notice you using MCSAT, I should warn you that:
```
void yices_stop_search(context_t* ctx)
```
is a no-op for the MCSAT solver.

**Comment by BrunoDutertre** [comment]
This discussion has migrated to issue #174
