### ISSUE TITLE
yices_stop_search not supported in MCSAT

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/yices2#174]
We should fix this. Is there really no way, currently, to stop the solver 
once  it has started in mcsat?

```
/*
 * Interrupt the search:
 * - this is not supported by mcsat yet
 */
void context_stop_search(context_t *ctx) {
  if (ctx->mcsat == NULL) {
    stop_search(ctx->core);
    if (context_has_simplex_solver(ctx)) {
      simplex_stop_search(ctx->arith_solver);
    }
  }
}
```

**Comment by dddejan** [comment]
Apart from some engineering within Yices, the main issue is that the libraries MCSAT depends on would need to support the same style of stopping the computation. LibPoly is one, Cudd is the other one. 

The main source of timeouts in MCSAT nonlinear solving is that it ends up computing with very large numbers. Once LibPoly get's going with large numbers and passes the computation over to GMP I'm not sure it's possible to stop it.

**Comment by dddejan** [comment]
It is probably possible to trigger similar non-responsive behavior in DPLL(T) part of Yices if Simplex get's stuck computing with large numbers. Is this right @BrunoDutertre?

**Comment by BrunoDutertre** [comment]
Yes, GMP can't be interrupted (but it's much less likely to get into
very expensive computation in the Simplex code than in non-linear problems).

**Comment by ianamason** [comment]
Just because we cannot always guarantee termination (from external library calls)
doesn't argue against a simple mechanism for stopping when one is able to.

*Don't let the perfect be the enemy of the good.*

**Comment by ffrohn** [comment]
I would appreciate that. I recently switched to Yices for linear arithmetic (in the tool [LoAT](https://github.com/aprove-developers/LoAT)), resulting in a significant speedup. However, I cannot use Yices for non-linear arithmetic due to this issue.

**Comment by ianamason** [comment]
So if you are using a Unix like system, you can fork a child to run the solver, and kill it
if your alarm goes off. If you need the answer or model, you could use some form of shared memory. Not elegant.

**Comment by dddejan** [comment]
Ok, I'll start working on this but it will require a bit of interaction.

I added some basic stuff to interrupt the search. If you can try it out and provide feedback then I can start fixing up cases where it requires more work.

**Comment by ffrohn** [comment]
Thanks! I ran a first test:

Yices for LIA only: 479 instances solved, avg runtime 4.79s
Yices for LIA & NIA: 474 instances solved, avg runtime 3.87s

So there's a nice speedup, but also a few regressions. I'll look into it next week to see if the regressions are caused by non-termination of mcsat.

**Comment by dddejan** [comment]
Just to make sure: if you enable MCSAT the LIA performance will go down. If possible you should only enable MCSAT on actual NIA problems. If you have mixed problems, the way we do this in our project is to have two solvers, one MCSAT other not, and both check the return value of the assert to see which one applies. See for example [here](https://github.com/SRI-CSL/sally/blob/090adb0b3ca07b63ef2fb66b92375f0b6f8835cb/src/smt/yices2/yices2_internal.cpp#L1063).

**Comment by ffrohn** [comment]
Thanks for the hint, I'm only using MCSAT for NIA. I can't reproduce the regressions reliably, but it seems like they are not related to non-termination of MCSAT.

Nevertheless, MCSAT sometimes takes a while to terminate after calling `yices_stop_search`. E.g., if I call `yices_stop_search` after 500ms it is sometimes still running after 750ms (I'm working with rather small timeouts).

Is there a way to pretty-print a context? Then I could try to dump some of those instances.

**Comment by dddejan** [comment]
Oh sorry for the later reply, I just noticed this.

I'm not sure printing the context is possible, or helpful for me. If you had a way to get a backtrace of the problematic instances at the time when they were interrupted, that would be helpful. 

Probably best way to debug this would be for me to run your tool. I would need clear instructions for easy setup and how to run a problematic minimal benchmark.

**Comment by dddejan** [comment]
@ffrohn The discussion stalled, just pinging. If there is a way for us to improve the timeout implementation let me know. Otherwise, I will close the bug until there is further issues.

**Comment by ffrohn** [comment]
i didn't have time to look into this issue again, but I didn't forget about it. I still want to dump those backtraces (running my tool is troublesome, since the build process is a bit messy), but it might take a while. Feel free to close the bug if you prefer, I'll get back to you when I have more information.
