### ISSUE TITLE
building libyices.a

### ISSUE THREAD

**Issue by ffrohn** [SRI-CSL/yices2#176]
I'm trying to build `libyices.a`. With my local installation of gmp, I got tons of errors like
```
/usr/bin/ld: /lib/x86_64-linux-gnu/libgmp.a(lt4-clear.o): relocation R_X86_64_PC32 against symbol `__gmp_free_func' can not be used when making a shared object; recompile with -fPIC
```
So I downloaded gmp and configured its build as follows:
```
./configure CFLAGS="-fPIC"
```
After compiling gmp, I reconfigured the Yices build as follows (where `$GMP` is the directory of the fresh gmp build):
```
./configure  --with-static-gmp=$GMP/.libs/libgmp.a --with-pic-gmp=$GMP/.libs/libgmp.a --with-static-gmp-include-dir=$GMP --with-pic-gmp-include-dir=$GMP --enable-mcsat
```
Still, `make static-lib` fails with the following  errors:
```
/usr/bin/ld: $GMP/.libs/libgmp.a(dive_1.o): relocation R_X86_64_PC32 against symbol `__gmp_binvert_limb_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: $GMP/.libs/libgmp.a(mode1o.o): relocation R_X86_64_PC32 against symbol `__gmp_binvert_limb_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: $GMP/.libs/libgmp.a(bdiv_q_1.o): relocation R_X86_64_PC32 against symbol `__gmp_binvert_limb_table' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
```
Configuring the Yices build with
```
./configure  --with-pic-gmp=$GMP/.libs/libgmp.a --with-pic-gmp-include-dir=$GMP --enable-mcsat
```
instead does not work either. So I guess there's still something wrong with my gmp build. How do I need to build gmp instead?

The behaviour is the same for the 2.6.1 release and the current HEAD of the master branch (40fdddc).

**Comment by ianamason** [comment]
Not sure if it will help you but there is a lot of building documentation.
For example:

https://github.com/SRI-CSL/yices2/blob/master/doc/GMP

**Comment by ffrohn** [comment]
Thank you very much, that solved it. I just looked at doc/COMPILING, but missed doc/GMP...
