### ISSUE TITLE
Array content is missing from get-model when SMT2 format is requested

### ISSUE THREAD

**Issue by emmanuel099** [SRI-CSL/yices2#177]
**Version**: Yices 2.6.2 (compiled from master 40fdddc5dfb74d19c216b42c653e22c17034c00a)
**Platform**: x86_64-pc-linux-gnu (release)

## Actual

Consider the following satisfiable example:
```smt
(set-logic QF_ALIA)

(declare-const arr1 (Array Int Bool))

(declare-const arr2 (Array Int Bool))
(assert (= arr2 (store arr1 10 true)))

(check-sat)

(get-model)
```
Running it with `yices-smt2 example.smt` produces the following model:
```smt
(= arr1 @fun_2)
(= arr2 @fun_5)
(function @fun_2
  (type (Array Int Bool))
  (default false))
(function @fun_5
  (type (Array Int Bool))
  (= (@fun_5 10) true)
  (default false))
```
Running it with `yices-smt2 --smt2-model-format example.smt` produces the following model:
```smt
(model
  (define-fun arr1 () (Array Int Bool) @fun_2)
  (define-fun arr2 () (Array Int Bool) @fun_5))
```
The array content is missing from the SMT2 model.

## Expected

Models in SMT2 format should give the array content similar to Yices own output format.

For example, Z3 gives the following model:
```smt
(model
  (define-fun arr1 () (Array Int Bool)
    ((as const (Array Int Bool)) false))
  (define-fun arr2 () (Array Int Bool)
    (store ((as const (Array Int Bool)) false) 10 true))
)
```

**Comment by BrunoDutertre** [comment]
Can you point me to the part of the SMT-LIB standard that specifies this?
I'm OK with imitating Z3 but I'm not sure the format above is actually what the
standard requiters.

**Comment by emmanuel099** [comment]
Thanks for your fast response!

> Can you point me to the part of the SMT-LIB standard that specifies this?

I can't. As far as I can see, this isn't standardized. Note 48 in Appendices of SMT-LIB Standard 2.6 (note 40 in SMT-LIB 2.5) explicitly mentions that the SMT-LIB standard doesn't impose stronger restrictions on the returned definitions, because of the limited expressive power of some theories, including the theory of arrays. 

But at the same time notes 45 & 48 (notes 37 & 40 in SMT-LIB 2.5) give an example of how arrays may be represented: `(store (store (store (as @array1 (Array Int Int)) 0 0) 1 2) 2 4))`.

CVC4 has a similar representation as Z3:
```smt
(model
(define-fun arr1 () (Array Int Bool) ((as const (Array Int Bool)) false))
(define-fun arr2 () (Array Int Bool) (store ((as const (Array Int Bool)) false) 10 true))
)
```

Boolector has a slightly different representation (example above adopted to bit vectors):
```smt
(set-option :produce-models true)

(set-logic QF_ABV)

(declare-const arr1 (Array (_ BitVec 8) (_ BitVec 1)))

(declare-const arr2 (Array (_ BitVec 8) (_ BitVec 1)))
(assert (= arr2 (store (store arr1 (_ bv1 8) (_ bv1 1)) (_ bv2 8) (_ bv1 1))))

(check-sat)

(get-model)
```
```smt
(model
  (define-fun arr2 (
   (arr2_x0 (_ BitVec 8))) (_ BitVec 1)
    (ite (= arr2_x0 #b00000010) #b1
    (ite (= arr2_x0 #b00000001) #b1
       #b0)))
)
```

**Comment by BrunoDutertre** [comment]
Done in 0fbeb5740e4f15e1b496ed5e446dbf356788e92c.

**Comment by emmanuel099** [comment]
Thank you very much! Works as expected.
