### ISSUE TITLE
yices> prompt now on stdout instead of stderr

### ISSUE THREAD

**Issue by SylvainCecchetto** [SRI-CSL/yices2#183]
Hi,

I just updated Yices from master and noticed that now the prompt (`yices>`) is send on stdout instead of stderr.
This new behavior breaks my parsing.

Do you now if we can disable the prompt of Yices?

Thank you!

Edit: Noticed this issue with `yices-smt2`

**Comment by BrunoDutertre** [comment]
How are you calling yices-smt2? We could disable the prompt is stdin is not a terminal.
Would that work for you?

**Comment by SylvainCecchetto** [comment]
I call `yices-smt2` from a C++ project with the [reproc](https://github.com/DaanDeMeyer/reproc) library (typically a fork/execv/dup2/pipe scenario).

**Comment by BrunoDutertre** [comment]
OK. Try the latest master: 3f6e0fce8f7bb559024ff27cafbdd272e21f7b42.

**Comment by SylvainCecchetto** [comment]
It's perfect! Thank you very munch for this fast fix! 🎉
