### ISSUE TITLE
Precompiled shared library download does not include dependencies

### ISSUE THREAD

**Issue by marcogario** [SRI-CSL/yices2#192]
I downloaded `yices-2.6.2-x86_64-pc-linux-gnu-static-gmp.tar.gz`, and the lib directory contains `libyices.so.2.6.2` . The library depends on 3 shared libraries that are not included: libcudd, libcadical, libcryptominisat. 

```
$ ldd libyices.so.2.6.2 
	linux-vdso.so.1 (0x00007ffd909d1000)
	libcudd-3.0.0.so.0 => not found
	libcadical.so => not found
	libcryptominisat5.so.5.6 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb7e18ac000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb7e2182000)
```

Therefore, I cannot load the dynamic library. I would expect those libraries to be included in the archive as dependencies. Was this an intentional omission?

Thanks!

**Comment by BrunoDutertre** [comment]
Should be fixed now. I've recompiled the library.
