### ISSUE TITLE
Sphinx 3 issues

### ISSUE THREAD

**Issue by jamesjer** [SRI-CSL/yices2#198]
The Fedora Linux distribution has started the process of switching from sphinx 2 to sphinx 3.  The yices package fails to build its documentation with sphinx 3.  There are two issues:
1. sphinx.locale.l_, which was deprecated in sphinx 2, has been removed entirely from sphinx 3.  This affects both sphinx extensions: cenum.py and cheader.py.  The _ function should be used instead.
1. Sphinx 3 provides an enum role and an enum directive, so cenum.py is not needed.  In fact, it doesn't work at all due to changes in CDomain in sphinx 3.

**Comment by BrunoDutertre** [comment]
Thanks Jerry. I'll look into this. Paradoxically, Sphinx's own documentation is still as horrible
as I remember.

**Comment by BrunoDutertre** [comment]
I've tried to fix ``conf.py`` in to handle this in https://github.com/SRI-CSL/yices2/commit/52d025a6b0ae2af55bf8f537ddeb9cd8f2519237.
 @jamesjer Can you check whether it works for you?

**Comment by jamesjer** [comment]
Thanks for the quick fix!  That commit does indeed resolve the issue.
