### ISSUE TITLE
Seemly wrong model

### ISSUE THREAD

**Issue by HanielB** [SRI-CSL/yices2#199]
In testing the model validator for the upcoming SMT-COMP (which we are going to use experimentally for the linear arithmetic logics QF_IDL, QF_RDL, QF_LIA, QF_LRA, QF_LIRA) I did a test run on StarExec with a few solvers, including [the version of Yices submitted to the Model Validation track ](https://www.starexec.org/starexec/secure/details/solver.jsp?id=24214). There was a single case in which a wrong model was reported by the validator, for the problem [QF_RDL/.../tms-2-3-light-60.smt2](https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/QF_RDL/blob/master/SMT-Temporal-Planning-Benchmarks/tms-2-3-light-60.smt2). The offending model is attached. I thought it might interest you. CVC4 produces a model that is accepted by the validator, also attached. I also checked the models with both CVC4 and Yices and the CVC4 models lead to both saying SAT and the Yices model to both saying UNSAT.

[models.tar.gz](https://github.com/SRI-CSL/yices2/files/4489551/models.tar.gz)

**Comment by BrunoDutertre** [comment]
Thanks @HanielB. This should be fixed now.
