### ISSUE TITLE
Random segfault with "big" SMTLIB file

### ISSUE THREAD

**Issue by SylvainCecchetto** [SRI-CSL/yices2#201]
With a big SMTLIB file (~1000 lines) I get random segfault running `yices-smt2`.

OS: macOS 10.15.14
Yices version: 2.6.2

Steps to reproduce:

1. Download `yices.smt2` file
2. Run `yices-smt2 yices.smt2` multiple times

The smtlib file contains only 22 times the same formula separated by 21 `(reset)`.

Thank you!

[yices.smt2.zip](https://github.com/SRI-CSL/yices2/files/4540406/yices.smt2.zip)

**Comment by BrunoDutertre** [comment]
Thanks for reporting this. bug . It should be fixed by baa669a5096ea10a6e0cd32ff5d84b1fbe01185b.

**Comment by SylvainCecchetto** [comment]
It's perfect! Thank you for this quick fix!
