### ISSUE TITLE
Exists-forall support in SMT-LIBv2?

### ISSUE THREAD

**Issue by boqwxp** [SRI-CSL/yices2#205]
Hi,

I can't figure out how to import and solve an exists-forall problem described in an SMT-LIBv2 file. Is this possible?

To be clear, I have no problems using the exists-forall mode with a native Yices problem file: `yices --mode=ef problem.yices`. But `yices --mode=ef problem.smt2` obviously doesn't work, and `yices-smt2 --mode=ef problem.smt2` doesn't work, as it doesn't understand the `--mode=ef` directive.

I have seen [this issue](https://github.com/pysmt/pysmt/issues/540) in another project, but it seems @gitsper's last comment on Nov. 10th confused SMT-LIBv2 and Yices languages.

If this is not supported, what would it take to support it?

For context, I am currently improving support for exists-forall problems in [Yosys](https://github.com/YosysHQ/yosys) and adding some example applications. I do have a working bitblasting native Yices backend, but: it's bitblasting, first of all, has questionable code quality, and is a few hundred lines of new code to maintain. At the same time, there is already robust SMT-LIBv2 support and a framework, `yosys-smtbmc` to interact with solvers, with which Z3 [works just fine for exists-forall problems](https://github.com/YosysHQ/yosys/blob/master/passes/sat/qbfsat.cc#L283). In the past, though, I've found that Yices' exists-forall solver offers best-in-class performance and I would very much like to support it, too.

So, if this is already supported somehow or not difficult to implement, it would greatly simplify my task to get Yices supported in Yosys for exists-forall problems.

**Comment by BrunoDutertre** [comment]
You don't need to do anything special. 

Write an SMT2 file with logic ``BV`` or ``LRA`` and the exists/forall solver will be
used. It may fail if the problem in question is not in the exists/forall fragment, but
it will try,

Here are two simple examples:
```
(set-logic LRA)
(declare-fun x () Real)
(assert (exists ((z Real)) (forall ((y Real)) (and (> x y) (> z y)))))
(check-sat)
(exit)
```

```
(set-logic BV)
(declare-fun y () (_ BitVec 12))
(assert
  (forall ((x0 (_ BitVec  12)))
    (or (not (= ((_ extract 11 10) y) ((_ extract 11 10)  (bvadd x0 x0))))
        (not (= ((_ extract 10 9) y) ((_ extract 10 9) (bvadd x0 x0))))
        (not (= ((_ extract 9 8) y) ((_ extract 9 8) (bvadd x0 x0))))
        (not (= ((_ extract 8 7) y) ((_ extract 8 7) (bvadd x0 x0))))
        (not (= ((_ extract 7 6) y) ((_ extract 7 6) (bvadd x0 x0))))
        (not (= ((_ extract 6 5) y) ((_ extract 6 5) (bvadd x0 x0))))
        (not (= ((_ extract 5 4) y) ((_ extract 5 4) (bvadd x0 x0))))
        (not (= ((_ extract 4 3) y) ((_ extract 4 3) (bvadd x0 x0))))
        (not (= ((_ extract 3 2) y) ((_ extract 3 2) (bvadd x0 x0))))
        (not (= ((_ extract 2 1) y) ((_ extract 2 1) (bvadd x0 x0))))
        (not (= ((_ extract 1 0) y) ((_ extract 1 0) (bvadd x0 x0)))))))
(check-sat)
(get-model)
```

**Comment by boqwxp** [comment]
D'oh!  The problem is only a missing `(set-logic BV)`.  Thanks for the example!

**Comment by boqwxp** [comment]
@BrunoDutertre Sorry for the issue necromancy, but I'd rather not add another issue just to ask a couple questions.

How much work would it take to support the following?
1) Proper optimization like [this](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/nbjorner-nuz.pdf) but in exists-forall mode (which Z3 does *not* support, either, just to be clear).
2) `BVLRA` or `BVLIA` logics (I guess that's what you'd call them?) in exists-forall mode.

As you might have seen from some of the [example .smt2](https://github.com/boqwxp/yosys-examples/blob/master/example1/example.smt2) files I've posted, I am making some problems typically composed of two parts.  The first part is basically a miter, some native-`BV` logic typically asserting equivalence (or pseudo-equivalence, with certain inequalities allowed) between two circuit submodules.  The second part takes the values for the existentially-quantified variables used in one of the submodules in the previous `BV` part, applies some scoring function to them (whose logic is properly `BV` I guess), and computes some function over those scores (typically, simple summation) that seems most naturally `LIA` or `LRA` but is currently required to be `BV`.

I then optimize that function value with a bisection method, calling Yices repeatedly with a different operand to a `bvult`.

A proper exists-forall optimization procedure would hopefully be much more efficient, reliable, and save lots of otherwise duplicated effort.  Being able to combine `BV` and `LIA` or `LRA` might make the second part of these problems easier to solve--or maybe not!  Please correct me if I'm wrong.
