### ISSUE TITLE
SMT-LIBv2 command `(get-value ...)` fails after exists-forall `(check-sat)`

### ISSUE THREAD

**Issue by boqwxp** [SRI-CSL/yices2#207]
Test case:
====
See [here](https://github.com/boqwxp/yices-bug).

Actual behavior:
====

When using `(get-value ...)` after a `(check-sat)` in a `BV`-logic exists-forall SMT-LIBv2 problem, I get the following error:
```
(error "can't build a model. Call (check-sat) first")
```

Obviously this is wrong, because I just called `(check-sat)`.  Interestingly, `(get-model)` still works (see `yices_out` in the test case repo).

Expected behavior:
====
Yices should print the specified value and not generate an error.  Z3, for example, has no trouble with the exact same input file (see `z3_out` in the test case repo).

**Comment by BrunoDutertre** [comment]
Should be fixed now.
