### ISSUE TITLE
inconsistent binary name 

### ISSUE THREAD

**Issue by aep** [SRI-CSL/yices2#213]
the downloads on https://yices.csl.sri.com/ use yices-smt2
but when building from source you get yices_smt2 and also yices_smt2_mt (whats the difference?)

```
aep@stark: ~/Downloads/yices-2.6.2/yices2 ls build/x86_64-pc-linux-gnu-release/bin/     
yices  yices_sat  yices_sat_new  yices_smt  yices_smt2  yices_smt2_mt  yices_smtcomp
```

````
tar xvf yices-2.6.2-x86_64-apple-darwin18.7.0-static-gmp.tar.gz | grep bin   
yices-2.6.2/bin/
yices-2.6.2/bin/yices-smt
yices-2.6.2/bin/yices-smt2
yices-2.6.2/bin/yices-sat
yices-2.6.2/bin/yices
```

**Comment by BrunoDutertre** [comment]
After you build from source with ``make`` or ``make dist``, look into
```
build/x86_64-pc-linux-gnu-release/dist/bin
```
But better, just do ``make install`` and the binaries will be in install-prefix/bin

**Comment by aep** [comment]
oh ok, so it is wish dash after all, thanks!
