### ISSUE TITLE
Failed to parse labeled assertion 

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#217]
Hi, for the following formula,
~~~~
(set-option :produce-unsat-cores true)
(set-logic QF_LIA)
(declare-const v0 Bool)
(declare-const v1 Bool)
(assert (= v1 v1 v0 v0) A)
~~~~

yices2 reports an error
~~~~
(error "at line 5, column 26: syntax error: ) expected")
~~~~

However, according to the manual https://yices.csl.sri.com/papers/manual.pdf (Page 32),
the formula above seems valid

**Comment by BrunoDutertre** [comment]
Page 32 is about the Yices language. You're using SMT-LIB2. This formula
is not syntactically correct in SMT-LIB2.
