### ISSUE TITLE
Delegate SAT solvers in EF mode / Assertion failure at smt_core.c:3971

### ISSUE THREAD

**Issue by boqwxp** [SRI-CSL/yices2#219]
I would like to try using cryptominisat as the delegate SAT solver in exists-forall mode.

To that end, [I modified `efsolve.c`](https://raw.githubusercontent.com/boqwxp/yices-bug/master/yices-bug-3/0001-Hard-code-cryptominisat-as-the-delegate-SAT-solver-f.patch) to replace `check_context()` with `check_with_delegate()`.  I tried it on [the standard example](https://github.com/boqwxp/yices-bug/raw/master/yices-bug-3/yices-bug-3.smt2) and got [this output](https://github.com/boqwxp/yices-bug/raw/master/yices-bug-3/yices_ef_delegate_cryptominisat.log.gz).

The last few lines are:
```
(EF: Found candidate model)
(EF: testing candidate against constraint 0)
(done flattening)
(asserting  630 top-level atoms)
(EF: candidate passed constraint 0)
(EF: testing candidate against constraint 1)
(done flattening)
(asserting  629 top-level atoms)
(asserting  1 top-level formulas)
(EF: candidate rejected: failed constraint 1)
(done flattening)
(asserting  1 top-level formulas)
(EF Iteration 1, scan_idx = 2)
yices-smt2: solvers/cdcl/smt_core.c:3971: add_simplified_binary_clause: Assertion `literal_is_unassigned(s, l0) && literal_is_unassigned(s, l1)' failed.
```

Is it not so straightforward to do this?  Or am I just forgetting something trivial like to reset some variable somewhere?

**Comment by BrunoDutertre** [comment]
That's not completely trivial. It's not enough to call ``check_with_delegate``.
The exists/forall solver also learns and adds a new assertion to the context (cf. function
``update_exists_context``). Adding new assertions after a call to check is not supported
 by the delegate mechanism.

You'd have to modify the ``exists_context`` by something that works with a delegate

**Comment by boqwxp** [comment]
Aha, I see.  Thanks.
