### ISSUE TITLE
Non-Linear Arithmetic with Quantifiers

### ISSUE THREAD

**Issue by kgoyal40** [SRI-CSL/yices2#228]
Hi,

I have an application which requires me to use ForAll quantifier over non-linear Arithmetic. I am aware that yices did not support formulas like these earlier and was under the impression that this functionality is being developed. Can you please let me know if this has been added to the solver?

Kshitij

**Comment by dddejan** [comment]
We do not currently support quantifiers in non-linear arithmetic. We are working in this direction but it is not something to be expected soon.
