### ISSUE TITLE
mcsat-assumptions: check-sat-assuming-model has side-effect

### ISSUE THREAD

**Issue by disteph** [SRI-CSL/yices2#233]
My understanding was that check-sat-assuming-model should not have a side effect.
Attached file finishes with
```
(check-sat)
(check-sat-assuming-model 
 (trig44 y!38 y!31 x1 y4 y3 y2 y1) 
 (true 
  #b00000000000000000000000000000000 
  #b11111111111111111111111111111111 
  #b00000000000000000000000000000000 
  #b00000000000000000000000000000000 
  #b00000000000000000000000000000000 
  #b00000000000000000000000000000000 
  #b00000000000000000000000000000000))
(check-sat)
```
First check-sat says SAT, check-sat-assuming-model says UNSAT, second check-sat says UNSAT
[RND_4_22.trace.smt2.zip](https://github.com/SRI-CSL/yices2/files/4775853/RND_4_22.trace.smt2.zip)

**Comment by disteph** [comment]
And here's the example, minimized:
```
(set-option :produce-unsat-model-interpolants true)
(set-logic QF_BV)
(declare-fun x () Bool)
(assert (not x))
(check-sat)
(get-model)
(check-sat-assuming-model (x) (true))
(check-sat)
```
command-line options are `--mcsat` and `--incremental`

**Comment by dddejan** [comment]
@disteph  check if it works, close if so

**Comment by disteph** [comment]
Looks good, at least for that example and the original smt2 problem from whence it came!
