### ISSUE TITLE
Assertion failure during Yices MBQI

### ISSUE THREAD

**Issue by aman-goel** [SRI-CSL/yices2#254]
Hi,

For the quantified UF formula:
```
(set-logic UF)
(declare-sort S 0)
(declare-fun a () S)
(declare-fun f (S S) S)
(declare-fun g (S S) S)
(assert (= (f a a) (f a (f a (f a a)))))
(assert (forall ((x S) (y S)) (= (f (f a a) a) (ite (= (f (f a x) a) a) a (ite (= (f (f a y) a) a) a (f a (f (g a x) y)))))))
(assert (forall ((x S) (y S)) (= (f a (f a y)) (f a (f (f a x) y)))))
(check-sat)
```
the experimental Yices MBQI [2937d9c](https://github.com/SRI-CSL/yices2/pull/234/commits/2937d9cbcded89773240e1324fb685c0e96fba1a) fails the following assertion in debug mode:

```
yices_smt2: terms/term_utils.c:117: collect_finite_domain: Assertion `term_kind(tbl, t) == ARITH_CONSTANT || term_kind(tbl, t) == BV64_CONSTANT || term_kind(tbl, t) == BV_CONSTANT' failed.
```

The failure looks to be dealing with nested ITEs and converting them to conditionals.
Several other SMT-LIB examples from UF/sledgehammer/TwoSquares/* are crashing for the same reason.

@BrunoDutertre - Any help would be great.

Thanks.

--
Aman

**Comment by BrunoDutertre** [comment]
Sure, I'll look into this.

**Comment by BrunoDutertre** [comment]
@aman-goel: It's fixed in yices2/master. The assertion was missing a case.
