### ISSUE TITLE
Deal with algebraic numbers in interpolation

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#262]
Hi, for the following formula

~~~~
(set-logic QF_UFNRA)
(declare-const r1 Real)
(declare-const r7 Real)
(assert (or (= (* r1 r1 5.7306 5.7306 r1) (- 5.7306) (- 5.7306))))
(check-sat-assuming-model ( r1 r7) (29354.0 61.85))
~~~~

yices 9d0f44b
~~~~
yices_smt2: mcsat/value.c:349: mcsat_value_to_term: Assertion `0' failed.
~~~~

**Comment by dddejan** [comment]
This example requires explaining algebraic numbers which is currently not supported. Better error handling is needed.

**Comment by dddejan** [comment]
Propagation of algebraic numbers has been disabled since we don't have a way to represent them as terms. This should fix it.
