### ISSUE TITLE
Is there any way to create constant arrays in Yices using the C API?

### ISSUE THREAD

**Issue by mikhailramalho** [SRI-CSL/yices2#271]
By constant arrays, I mean an array where all positions are initialized to the same value.

The documentation hints that it is possible:
```
 * All functions used in the model have a simple form. They are defined
 * by a finite list of mappings and a default value. Each mapping specifies the
 * value of the function at a single point in its domain. For example, we could
 * have a function f of type [int, int -> int] defined by the clauses:
 *    f(0, 0) = 0
 *    f(3, 1) = 1
 *    f(x, y) = -2 in all other cases.
```
but I couldn't find a way to set default value -2 using the C API.

**Comment by BrunoDutertre** [comment]
Hi @mikhailramalho,

Sorry for the delayed answer. The way to construct a constant array is to use lambda terms.
For Yices, a constant array is the same as a constant function like ``(lambda (i: int) false)``. 
But, at moment, Yices is very restricted on what it can do with such lambda terms. We're working
on it, but it's not well supported yet.

**Comment by mikhailramalho** [comment]
Thank you for your reply, Bruno.

I found `yices_lambda` but we have to create a vector vars for each element in the array, am I right? 

Is there a simpler way to create the lambda through the C API, like in your example? I mean, where you only set the index type and the default value?

**Comment by BrunoDutertre** [comment]
You need only one variable, namely, the integer ``i`` in ``(lambda (i: int) xxx)``.
For example to create "lambda (I:int) false":
```
    term_t i = yices_new_variable(yices_int_type());
    term_t l = yices_lambda(1, &I, yices_false());
```

But, as I wrote before, being able to create the lambda term won't get you very far,
because the array solver does not support these lambda terms yet.

**Comment by mikhailramalho** [comment]
Understood, Bruno, thanks.

**Comment by disteph** [comment]
I'm closing this issue as it seems the conversation has concluded.
