### ISSUE TITLE
Idea to improve speed with my Yices usage?

### ISSUE THREAD

**Issue by sy6sy2** [SRI-CSL/yices2#284]
Hi all,

First of all thank you for this solver! I use it everyday inside a binary tool analysis that I am developing for my thesis. I don't know if you can help me but I will try anyway.

## Context

My project is a C++ program whose goal is to build the control flow graph of an unknown binary program. The idea is to alternate between static disassembly and symbolic execution until a fixed point. At the fixed point we hope to have all the assembly instructions code of the program.

## What about Yices?

In order to symbolically execute some pieces of the program I use SMT solvers (already tried Z3, CVC4, boolector and Yices but Yices seems to be the faster solver for my usage).

Let's say I want to symbolically execute some assembly instructions with specific entries values. My process is to "translate" assembly code in SMTLIBv2 formula:

`x86 instructions --> intermediate language --> SMTLIBv2 formula`

My final step is to give the SMTLIBv2 formula to Yices in order to obtain the SAT values of the registers and memory cells at the end of the symbolic execution. To do that I simply use `assert` for my entry contrains, `define-fun` for my variables updates and `check-sat` and `get-values` to obtain final values. Also, I use BitVector variables for my CPU registers and a BitVector array to represent the memory).

## Simple example

Let's say I have this piece of code that I want to symbolically execute:

```asm
ADD EBX, EAX    ; EBX <-- EAX + EBX
SUB ECX, EBX    ; ECX <-- ECX - EBX
```

Also, I have the current entry values: `EAX = 0x1`, `EBX = 0x2` and `ECX = 0x8`.
Of course, "by hand" we can easily find that at the end of this execution we will have `EAX = 0x1`, `EBX = 0x3` and `ECX = 0x5`, but we will use Yices to do that:

After the translation I obtain this final SMTLIB formula:

```SMT
(set-option :produce-models true)
(set-logic QF_ABV)

; Variables declaration
(declare-fun eax0 () (_ BitVec 32))
(declare-fun ebx0 () (_ BitVec 32))
(declare-fun ecx0 () (_ BitVec 32))

; Entry contraints
(assert (= eax0 (_ bv1 32)))
(assert (= ebx0 (_ bv2 32)))
(assert (= ecx0 (_ bv8 32)))

; Code instructions representation
(define-fun ebx1 () (_ BitVec 32) (bvadd ebx0 eax0))    ; ADD EBX, EAX
(define-fun ecx1 () (_ BitVec 32) (bvsub ecx0 ebx1))    ; SUB ECX, EBX

; Get final values
(check-sat)
; Do not ask for EAX final value because I already know that EAX register is not modified by this code
(get-value (ebx1 ecx1))
```

## How is it in the real world?

Of course this exemple is really simple but in reality I need to deal with bigger formula (no more that ~30 assembly instructions).
I noticed that during the execution of my tool, 90% of the time is spend in Yices (during the `(check-sat)` step I guess?).
For a "simple" binary program I have to apply ~1000000 SMTLIB formula to Yices (so ~1000000 `(check-sat)`, `get-value` and `(reset)`).
This is what I currently do in order to obtain the best time:

* I do not give unused contrains in the formula (in my previous exemple, I will not put `(assert (= edx0 (_ bv24 32)))` because I already know that the `EDX` register is not used by my instructions)
* I call `(reset)` between each symbolic execution (also, I do not use `(push)` and `(pop)` commands)
* I communicate with Yices through pipes with a subprocess (I use [reproc library](https://github.com/DaanDeMeyer/reproc) and I open Yices with `yices-smt2 --bvconst-in-decimal` command)

## Idea to improve my usage of Yices

I know that this is not really an issue because Yices works well for my usage. But I am wondering if I can improve my process somewhere in order to reduce the time I spend using Yices in my program. Of course if I can win some milliseconds on every call to Yices at the end it worth it 😉.

* Should I use the C API instead of my `fork-execv-pipe`? (IIRC, last time I checked the C API does not offer `get-value` with multiple variables. Also, my intermediate language directly give me each assembly instruction in SMTLIBv2 format so I need to parse each SMTLIB command to use C objects of the API)
* Can I "by-pass" the `(check-sat)` step because I already know that the formula is `SAT`? But I guess that this step is mandatory to obtain the model and use `get-value`?
* Do I miss something else?

Thank you very munch for the time spend reading this message and for your help!

**Comment by BrunoDutertre** [comment]
Hi @sy6sy2,

Thanks for using Yices and for the positive feedback.

I would like to clarify something about your use case.
Your example starts with this:
```SMT
; Variables declaration
(declare-fun eax0 () (_ BitVec 32))
(declare-fun ebx0 () (_ BitVec 32))
(declare-fun ecx0 () (_ BitVec 32))

; Entry contraints
(assert (= eax0 (_ bv1 32)))
(assert (= ebx0 (_ bv2 32)))
(assert (= ecx0 (_ bv8 32)))
```
So you have three variables and three assertions that assign a value to each.
After that, the value of all the other variables (``ebx1``, ``ecx1``) are uniquely
defined. Are your examples all like that?

**Comment by sy6sy2** [comment]
Thank you for your reply!

Yes all my examples are like that. The structure of all my examples are:

1. *n* variables declarations with 32 bits size:
    * `(declare-fun eax0 () (_ BitVec 32))`
    * `(declare-fun ebx0 () (_ BitVec 32))`
    * ... 
2. *m* variables declarations with 1 bit size:
    * `(declare-fun OF0 () (_ BitVec 1))`
    * `(declare-fun SF0 () (_ BitVec 1))`
    * ... 
3. My unique array declaration (used to represent the computer memory):
    * `(declare-fun memory0 () (Array (_ BitVec 32) (_ BitVec 8)))`

4. *x* entry constraints (assignations) on my 32 bits variables:
    * `(assert (= eax0 (_ bv1 32)))`
    * `(assert (= ebx0 (_ bv2 32)))`
    * ...

5. *y* entry constraints (assignations) on my 1 bits variables:
    * `(assert (= OF0 (_ bv1 1)))`
    * `(assert (= SF0 (_ bv0 1)))`
    * ...

6. *z* entry constraints (assignations) on array cells:
    * `(assert (= (select memory0 (_ bv2147348482 32)) (_ bv7 8)))`
    * `(assert (= (select memory0 (_ bv2147348483 32)) (_ bv0 8)))`
    * `(assert (= (select memory0 (_ bv458748 32)) (_ bv40 8)))`
    * ...

7. Code representation with all the `define-fun` lines:

```
(define-fun memory1 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory0 (bvsub esp0 (_ bv4 32)) (_ bv196 8)) (bvsub esp0 (_ bv3 32)) (_ bv19 8)) (bvsub esp0 (_ bv2 32)) (_ bv0 8)) (bvsub esp0 (_ bv1 32)) (_ bv1 8)))
(define-fun esp1 () (_ BitVec 32) (bvsub esp0 (_ bv4 32)))
(define-fun eax1 () (_ BitVec 32) (concat (select memory1 (bvadd fs_base0 (_ bv3 32))) (concat (select memory1 (bvadd fs_base0 (_ bv2 32))) (concat (select memory1 (bvadd fs_base0 (_ bv1 32))) (select memory1 fs_base0)))))
(define-fun memory2 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory1 (bvsub esp1 (_ bv4 32)) ((_ extract 7 0) eax1)) (bvsub esp1 (_ bv3 32)) ((_ extract 15 8) eax1)) (bvsub esp1 (_ bv2 32)) ((_ extract 23 16) eax1)) (bvsub esp1 (_ bv1 32)) ((_ extract 31 24) eax1)))
(define-fun esp2 () (_ BitVec 32) (bvsub esp1 (_ bv4 32)))
(define-fun memory3 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory2 fs_base0 ((_ extract 7 0) esp2)) (bvadd fs_base0 (_ bv1 32)) ((_ extract 15 8) esp2)) (bvadd fs_base0 (_ bv2 32)) ((_ extract 23 16) esp2)) (bvadd fs_base0 (_ bv3 32)) ((_ extract 31 24) esp2)))
(define-fun eax2 () (_ BitVec 32) (concat (select memory3 (bvadd esp2 (_ bv19 32))) (concat (select memory3 (bvadd esp2 (_ bv18 32))) (concat (select memory3 (bvadd esp2 (_ bv17 32))) (select memory3 (bvadd esp2 (_ bv16 32)))))))
(define-fun memory4 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory3 (bvadd esp2 (_ bv16 32)) ((_ extract 7 0) ebp0)) (bvadd esp2 (_ bv17 32)) ((_ extract 15 8) ebp0)) (bvadd esp2 (_ bv18 32)) ((_ extract 23 16) ebp0)) (bvadd esp2 (_ bv19 32)) ((_ extract 31 24) ebp0)))
(define-fun ebp1 () (_ BitVec 32) (bvadd esp2 (_ bv16 32)))
(define-fun res320 () (_ BitVec 32) (bvsub esp2 eax2))
(define-fun OF1 () (_ BitVec 1) (bvand (bvnot (bvcomp ((_ extract 31 31) esp2) ((_ extract 31 31) eax2))) (bvnot (bvcomp ((_ extract 31 31) esp2) ((_ extract 31 31) res320)))))
(define-fun SF1 () (_ BitVec 1) (ite (bvslt res320 (_ bv0 32)) (_ bv1 1) (_ bv0 1)))
(define-fun ZF1 () (_ BitVec 1) (bvcomp res320 (_ bv0 32)))
(define-fun AF1 () (_ BitVec 1) (ite (bvult ((_ extract 3 0) esp2) ((_ extract 3 0) eax2)) (_ bv1 1) (_ bv0 1)))
(define-fun PF1 () (_ BitVec 1) (bvnot (bvxor (bvxor (bvxor (bvxor (bvxor (bvxor (bvxor ((_ extract 0 0) res320) ((_ extract 1 1) res320)) ((_ extract 2 2) res320)) ((_ extract 3 3) res320)) ((_ extract 4 4) res320)) ((_ extract 5 5) res320)) ((_ extract 6 6) res320)) ((_ extract 7 7) res320))))
(define-fun CF1 () (_ BitVec 1) (ite (bvult esp2 eax2) (_ bv1 1) (_ bv0 1)))
(define-fun esp3 () (_ BitVec 32) res320)
(define-fun memory5 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory4 (bvsub esp3 (_ bv4 32)) ((_ extract 7 0) ebx0)) (bvsub esp3 (_ bv3 32)) ((_ extract 15 8) ebx0)) (bvsub esp3 (_ bv2 32)) ((_ extract 23 16) ebx0)) (bvsub esp3 (_ bv1 32)) ((_ extract 31 24) ebx0)))
(define-fun esp4 () (_ BitVec 32) (bvsub esp3 (_ bv4 32)))
(define-fun memory6 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory5 (bvsub esp4 (_ bv4 32)) ((_ extract 7 0) esi0)) (bvsub esp4 (_ bv3 32)) ((_ extract 15 8) esi0)) (bvsub esp4 (_ bv2 32)) ((_ extract 23 16) esi0)) (bvsub esp4 (_ bv1 32)) ((_ extract 31 24) esi0)))
(define-fun esp5 () (_ BitVec 32) (bvsub esp4 (_ bv4 32)))
(define-fun memory7 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory6 (bvsub esp5 (_ bv4 32)) ((_ extract 7 0) edi0)) (bvsub esp5 (_ bv3 32)) ((_ extract 15 8) edi0)) (bvsub esp5 (_ bv2 32)) ((_ extract 23 16) edi0)) (bvsub esp5 (_ bv1 32)) ((_ extract 31 24) edi0)))
(define-fun esp6 () (_ BitVec 32) (bvsub esp5 (_ bv4 32)))
(define-fun eax3 () (_ BitVec 32) (concat (select memory7 (bvsub ebp1 (_ bv5 32))) (concat (select memory7 (bvsub ebp1 (_ bv6 32))) (concat (select memory7 (bvsub ebp1 (_ bv7 32))) (select memory7 (bvsub ebp1 (_ bv8 32)))))))
(define-fun memory8 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory7 (bvsub ebp1 (_ bv24 32)) ((_ extract 7 0) esp6)) (bvsub ebp1 (_ bv23 32)) ((_ extract 15 8) esp6)) (bvsub ebp1 (_ bv22 32)) ((_ extract 23 16) esp6)) (bvsub ebp1 (_ bv21 32)) ((_ extract 31 24) esp6)))
(define-fun memory9 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory8 (bvsub esp6 (_ bv4 32)) ((_ extract 7 0) eax3)) (bvsub esp6 (_ bv3 32)) ((_ extract 15 8) eax3)) (bvsub esp6 (_ bv2 32)) ((_ extract 23 16) eax3)) (bvsub esp6 (_ bv1 32)) ((_ extract 31 24) eax3)))
(define-fun esp7 () (_ BitVec 32) (bvsub esp6 (_ bv4 32)))
(define-fun eax4 () (_ BitVec 32) (concat (select memory9 (bvsub ebp1 (_ bv1 32))) (concat (select memory9 (bvsub ebp1 (_ bv2 32))) (concat (select memory9 (bvsub ebp1 (_ bv3 32))) (select memory9 (bvsub ebp1 (_ bv4 32)))))))
(define-fun memory10 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory9 (bvsub ebp1 (_ bv4 32)) (_ bv255 8)) (bvsub ebp1 (_ bv3 32)) (_ bv255 8)) (bvsub ebp1 (_ bv2 32)) (_ bv255 8)) (bvsub ebp1 (_ bv1 32)) (_ bv255 8)))
(define-fun memory11 () (Array (_ BitVec 32) (_ BitVec 8)) (store (store (store (store memory10 (bvsub ebp1 (_ bv8 32)) ((_ extract 7 0) eax4)) (bvsub ebp1 (_ bv7 32)) ((_ extract 15 8) eax4)) (bvsub ebp1 (_ bv6 32)) ((_ extract 23 16) eax4)) (bvsub ebp1 (_ bv5 32)) ((_ extract 31 24) eax4)))
(define-fun esp8 () (_ BitVec 32) (bvadd esp7 (_ bv4 32)))
```

8. `check-sat`

9. `get-value` on multiples variables and array cells:

```
(get-value ((concat (select memory11 (bvadd (bvsub esp1 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp1 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp1 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp1 (_ bv4 32)))))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv8 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv8 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv8 32)) (_ bv1 32))) (select memory11 (bvsub ebp1 (_ bv8 32)))))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub ebp1 (_ bv4 32)))))) (concat (select memory11 (bvadd (bvsub esp6 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp6 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp6 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp6 (_ bv4 32)))))) (concat (select memory11 (bvadd (bvsub esp0 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp0 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp0 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp0 (_ bv4 32)))))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv24 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv24 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub ebp1 (_ bv24 32)) (_ bv1 32))) (select memory11 (bvsub ebp1 (_ bv24 32)))))) (bvsub esp1 (_ bv4 32)) (bvsub ebp1 (_ bv24 32)) (concat (select memory11 (bvadd (bvsub esp5 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp5 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp5 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp5 (_ bv4 32)))))) CF1 (concat (select memory11 (bvadd (bvsub esp4 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp4 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp4 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp4 (_ bv4 32)))))) (bvsub esp3 (_ bv4 32)) fs_base0 ebp1 (bvsub esp5 (_ bv4 32)) (concat (select memory11 (bvadd (bvadd esp2 (_ bv16 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvadd esp2 (_ bv16 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvadd esp2 (_ bv16 32)) (_ bv1 32))) (select memory11 (bvadd esp2 (_ bv16 32)))))) (bvsub ebp1 (_ bv4 32)) (bvsub esp4 (_ bv4 32)) eax4 (bvsub ebp1 (_ bv8 32)) (bvadd esp2 (_ bv16 32)) AF1 PF1 (bvsub esp8 (_ bv4 32)) jumplocationexpr0 (concat (select memory11 (bvadd fs_base0 (_ bv3 32))) (concat (select memory11 (bvadd fs_base0 (_ bv2 32))) (concat (select memory11 (bvadd fs_base0 (_ bv1 32))) (select memory11 fs_base0)))) ZF1 esp8 SF1 (bvsub esp6 (_ bv4 32)) (concat (select memory11 (bvadd (bvsub esp3 (_ bv4 32)) (_ bv3 32))) (concat (select memory11 (bvadd (bvsub esp3 (_ bv4 32)) (_ bv2 32))) (concat (select memory11 (bvadd (bvsub esp3 (_ bv4 32)) (_ bv1 32))) (select memory11 (bvsub esp3 (_ bv4 32)))))) (bvsub esp0 (_ bv4 32)) OF1))
```

10. Done for this formula. Now `reset` and goto point 1 with another formula with different constrains and code representation


If you need I can attack here some real example in smt2 format.

Thank you!

**Comment by BrunoDutertre** [comment]
You could merge 1 and 3. 

Instead of 
```smt
(declare-fun eax0 () (_ BitVec 32))
(assert (= eax0 (_ bv1 32)))
```
Use define-fun:
```smt
(define-fun eax0 () (_ BitVec 32) (_ bv1 32))
```
You could to the same thing for 2 and 4. 

That should lead to more efficient simplifications.

**Comment by sy6sy2** [comment]
Thank you for your advice.
I modified my code to use define-fun instead of declare-fun/assert but I don't notice any speed improvement with my tests.

I will trigger a timer before and after each `check-sat` call just to be sure that this where my program spends most of its time.

**Comment by sy6sy2** [comment]
After some tests it seems that my program spends most of its time waiting the `(get-value)` answer from Yices (90% of the program time).
I guess there is nothing I can do to improve this?
Thank you.

**Comment by BrunoDutertre** [comment]
Yes, there's not much you can do to accelerate ``(get-value).``

You could try to simplify the terms to evaluate a bit (e.g., one concat with four arguments instead
of nested binary concats). but that's probably not going to make a noticeable difference.

**Comment by sy6sy2** [comment]
Ok. Either way, thank you very much for your time helping me.

Yices remains the faster SMT solver that support Bit-vector array and the `(reset)` command in my case study.
