### ISSUE TITLE
Solution soundness bug on QF_LIRA formulas

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#302]
Hi, for the following formula,
yices 50199207dc yields `sat`, but z3 and cvc4 return `unsat`.
~~~~
(set-logic ALL)
(declare-fun _substvar_100_ () Real)
(declare-fun _substvar_112_ () Real)
(declare-const i5 Int)
(declare-const r1 Real)
(assert (xor true true true (> r1 0.0) true true false true true))
(assert (= (+ 0.0 r1 0.816061 0.0 r1) (to_real i5) r1 _substvar_112_ _substvar_100_))
(check-sat)
~~~~

- After changing `(set-logic ALL)` to `(set-logic QF_LIRA)` yices still gives the wrong anser
- After changing `(set-logic ALL)` to `(set-logic QF_NIRA)`, yices can work correctly.

**Comment by rainoftime** [comment]
Possibly related discussion https://github.com/SRI-CSL/yices2/issues/84

**Comment by rainoftime** [comment]
~~~~
(set-logic ALL)
(declare-const i8 Int)
(declare-const r11 Real)
(assert (<= 0.0 0.0 0.0 r11 r11))
(assert (= (to_real i8) 0.9125 r11))
(check-sat)
~~~~

**Comment by rainoftime** [comment]
For the following formula,
yices still gives the wrong answer after I use `(set-logic QF_LIRA)`
~~~~
(set-logic QF_LIRA)
(declare-const i8 Int)
(declare-const r11 Real)
(assert (<= 0.0 0.0 0.0 r11 r11))
(assert (= (to_real i8) 0.9125 r11))
(check-sat)
~~~~

**Comment by BrunoDutertre** [comment]
I can't reproduce this. For me, yices 50199207dc6ab843b0f3efa557140b3d6ea18e96 returns unsat on both examples.

**Comment by rainoftime** [comment]
Perhaps related to libpoly? (my libpoly version is  4be69fb721fbb)

**Comment by dddejan** [comment]
I also can't reproduce.

**Comment by BrunoDutertre** [comment]
It happens with --incremental only.

**Comment by dddejan** [comment]
> It happens with --incremental only.

Not for me

```console
CSL-CAS16427:yices2 dejan$ ./yices_smt2 issue302.smt2 
unsat
CSL-CAS16427:yices2 dejan$ ./yices_smt2 --incremental issue302.smt2 
unsat
```

**Comment by BrunoDutertre** [comment]
Which commit?

**Comment by dddejan** [comment]
Yices: dcd27ebe49f667c30ca825a8f6f471a5644aadc5
Libpoly: 4be69fb721fbb8fd09a49c19fdd7f59c19a72c19 (not relevant)

**Comment by BrunoDutertre** [comment]
That's the commit I just pushed to fix this bug.

**Comment by dddejan** [comment]
> That's the commit I just pushed to fix this bug.

Confusing, but great :)
