### ISSUE TITLE
Nary division

### ISSUE THREAD

**Issue by nafur** [SRI-CSL/yices2#311]
SMT-LIB specifies arithmetic division as n-ary (`(/ Real Real Real :left-assoc)`) and the yices manual states that `In general, all associative operations can take one, two, or more arguments` without listing division as an exception.
Nevertheless:
```
$ cat test.smt2 
(set-logic QF_NRA)
(declare-const r Real)
(assert (= 1.0 (/ 2 r r)))

$ yices-smt2-2.6.2 test.smt2 
(error "at line 3, column 17: wrong number of arguments in division")
```

**Comment by BrunoDutertre** [comment]
Thanks for reporting this, but division is not associative.

**Comment by nafur** [comment]
If by "division" you mean the SMTLIB operator `div`, I respectfully disagree: http://smtlib.cs.uiowa.edu/theories-Reals.shtml notes `(/ Real Real Real :left-assoc)`. If you mean the mathematical operation of division, wikipedia disagrees (https://en.wikipedia.org/wiki/Division_(mathematics)#Introduction).

**Comment by BrunoDutertre** [comment]
Of course, I mean the standard definition of associativity. The SMT-LIB annotation 
is just a rule for interpreting ``(/ a b c d)``.  This rule does not make ``/`` associative,
which means that the Yices manual does not need fixing and that ``/`` is not
an exception.

I will fix the SMT-LIB parser to allow this n-ary division.

**Comment by nafur** [comment]
I see. Thanks!

**Comment by BrunoDutertre** [comment]
Done in 7e7261ba6a9325aa94f54195ce9b5a688d86791a.
