### ISSUE TITLE
MCSAT incremental mode does not support NIRA formula 

### ISSUE THREAD

**Issue by rainoftime** [SRI-CSL/yices2#336]
Hi, for the following formula
~~~~
(set-logic QF_UFNIRA)
(declare-fun r2 () Real)
(assert (is_int r2))
(check-sat)
~~~~
At commit 238592b9d6e8e,
`yices_smt2 --incremental f.smt2` yields
~~~~
(error "mcsat: unsupported theory")
~~~~

`yices_smt2 f.smt2` works well. 
Replacing `(set-logic QF_UFNIRA)` with `(set-logic ALL)` also works.

**Comment by BrunoDutertre** [comment]
@dddejan: mcat does not support is_int, which causes this exception.

In non-incremental mode, yices checks whether the assertions are trivially sat.
This check succeeds and mcat does not even see the assertion.
