### ISSUE TITLE
abs is undefined in QF_NRA

### ISSUE THREAD

**Issue by junzew** [SRI-CSL/yices2#341]
Hi, there seems to be a parsing error for the absolute value function "abs" in the QF_NRA logic.
```
$cat bug.smt2
(set-logic QF_NRA)
(declare-fun s () Real)
(assert (= s (abs 100)))
(check-sat)
(exit)
$z3 bug.smt2 
sat
$yices-smt2 bug.smt2
(error "at line 3, column 15: undefined term: abs")
```

**Comment by BrunoDutertre** [comment]
The QF_NRA theory is Reals: http://smtlib.cs.uiowa.edu/theories-Reals.shtml.
There's no abs operation defined there.
