### ISSUE TITLE
BVXOR3 yields inconsistent result

### ISSUE THREAD

**Issue by 0152la** [SRI-CSL/yices2#353]
Using the C API of Yices2 commit 7e3815d5bbf80fd39155ca39bda9ac18af02465d, compiled with `mcsat` support, when passing three one-bit vectors with values (0b1, 0b1, 0b0) to `bvxor3`, the result is `0b1`, which is inconsistent with the expected result `0b0` (as returned by pairwise `bvxor2` and `bvxor(3, {0b1, 0b1, 0b0})`). With the appropriate setup, the following small snippet should return the incorrect result:

```
term_t t1 = yices_bvconst_minus_one(1);
term_t t2 = yices_bvconst_minus_one(1);
term_t zero = yices_bvconst_zero(1);
yices_pp_term(stdout, yices_bvxor3(t1, t2, zero), 5, 1, 0);
```

Attached are the [config.log](https://github.com/SRI-CSL/yices2/files/6164917/config.log) used to built the tool, and an archive [xor3_test.zip](https://github.com/SRI-CSL/yices2/files/6164943/xor3_test.zip) with the test file used to expose the inconsistency, as well as other ways of computing a three-way `xor`, which produce the correct result.

**Comment by dddejan** [comment]
Thanks for reporting. This was a typo. Should be fixed now.

**Comment by 0152la** [comment]
Confirmed fixed. Thanks.

**Comment by 0152la** [comment]
As a follow-up, may I ask if this typo would have been able to be exposed via an SMT-LIB input, or does this operation exist for use exclusively at the API level?

**Comment by BrunoDutertre** [comment]
It's purely an API problem.
