### ISSUE TITLE
Does yices support set-info command?

### ISSUE THREAD

**Issue by zvonimir** [SRI-CSL/yices2#355]
Hi,
We have this simple query generated by Boogie:
```
(set-option :print-success false)
(set-info :smt-lib-version 2.6)
(set-option :produce-models true)
(set-option :smt.qi.eager_threshold 100)
(set-option :smt.arith.solver 2)
(set-option :smt.array.extensional false)
(set-logic ALL)
```
When I run `yices-smt2 output1.smt2` on this query (with the latest release of yices), I get the following output:
```
Illegal instruction
```
When I comment out the `set-info` command, this problem disappears. So to me it seems that yices does not support `set-info`.
Is that right? Or am I missing something here?
I would appreciate your help to get to the bottom of this. Thanks!

**Comment by dddejan** [comment]
On my mac I get 

```bash
$ ./yices_smt2 test.smt2 
unsupported
unsupported
unsupported
```

The `Illegal instruction` problem we have seen before #120, #98. Can you give us more info on your setup.

**Comment by BrunoDutertre** [comment]
Illegal instruction is most likely a hardware incompatibility. You may have to build Yices
from source to fix it. See [here](https://yices.csl.sri.com/faq.html).

**Comment by zvonimir** [comment]
We are running it from the binary installation on Ubuntu 20.04. We download the binaries from here: https://yices.csl.sri.com/releases/2.6.2/yices-2.6.2-x86_64-pc-linux-gnu-static-gmp.tar.gz
We can try building it from source to see if that helps. Thanks for the suggestion.

**Comment by BrunoDutertre** [comment]
You can also double check that avx2 is supported on your machine with
```
grep avx2 /proc/cpuinfo
```

**Comment by jmcmillan1** [comment]
`grep avx2 /proc/cpuinfo`

Entering the above command produced no output

**Comment by BrunoDutertre** [comment]
This explains the ``Illegal Instruction`` error.  The GMP library packaged with Yices requires support
for the AVX2 instructions. If you build Yices from source, it will link with whatever version of GMP is
 on the build machine and you should be fine,

**Comment by zvonimir** [comment]
Thanks for your help! We are building it from source now and we do not have this problem any more.
