### ISSUE TITLE
why your website is closed? I want to learn some Yices' own specification language.

### ISSUE THREAD

**Issue by yuanyuan1024** [SRI-CSL/yices2#357]

**Comment by dddejan** [comment]
https://yices.csl.sri.com/

This website? It works for me. What kind of error are you seeing?

**Comment by yuanyuan1024** [comment]
> https://yices.csl.sri.com/
> 
> This website? It works for me. What kind of error are you seeing?

it says that I can not access this page.

**Comment by ianamason** [comment]
Where are you @yuanyuan1024 ?

**Comment by yuanyuan1024** [comment]
> Where are you @yuanyuan1024 ?

Shanghai, China.

**Comment by dddejan** [comment]
> > Where are you @yuanyuan1024 ?
> 
> Shanghai, China.

We're trying to figure this out. Could you please give us your IP address.

**Comment by BrunoDutertre** [comment]
@yuanyuan1024.

Apologies for the website problem. We're trying to get it fixed.

In case this helps, you can generate the doc for Yices yourself.
You need to install the Sphinx tool (e.g., with pip):
```
pip install Sphinx
```

Then do this:
```
git clone https://github.com/SRI-CSL/yices2.git
cd doc/sphinx
 make html
```
The doc will be in ``doc/sphinx/build/html``.

**Comment by disteph** [comment]
We have just migrated https://yices.csl.sri.com/ to a new server.
Do you still have an issue accessing it?

**Comment by ahmed-irfan** [comment]
@yuanyuan1024 
Is this still an issue?

**Comment by ahmed-irfan** [comment]
Reopen this if it is still an issue.
