### ISSUE TITLE
Question about trivial unsat context state (minor)

### ISSUE THREAD

**Issue by makaimann** [SRI-CSL/yices2#358]
Thank you for all your work on yices2! I have a (relatively unimportant) question about the yices2 API vs binary related to [this smt-switch issue](https://github.com/makaimann/smt-switch/issues/218). 

I recently added an SMT-LIB parser and ran with different solver backends on SMT-LIB divisions. In a few cases, the assertions in an incremental benchmark result in a trivial unsat context before the end of the file. Then I get errors when trying to use API functions (e.g. `the context state does not allow operation`). 

Based on my understanding, this is because it is in `STATUS_UNSAT` as described here: https://yices.csl.sri.com/doc/context-operations.html#assertions-and-satisfiability-checks. This of course makes sense because all future queries will return unsat. However, it would be nice to still be able to finish processing the benchmark. Furthermore, I noticed that the `yices_smt2` binary will handle it without throwing an error. For example, on this benchmark: [trivial-unsat.smt2.zip](https://github.com/SRI-CSL/yices2/files/6265820/trivial-unsat.smt2.zip), it prints `unsat`.

Is this a workaround in the parser? Or is there a way to return to `STATUS_IDLE` without removing all assertions?

Thanks for your time and please let me know if I can clarify anything.

**Comment by BrunoDutertre** [comment]
The main problem is push. The API does not allow push if the context is unsat.
The work around is to treat push as a no-op when the context is unsat. 
We do this In the Yices SMT2 frontend, and we  keep a counter ``push_after_unsat``
to match the number of calls to ``pop`` and ``push``.

**Comment by makaimann** [comment]
Got it, thanks for the workaround!
