### ISSUE TITLE
Static yices binary is broken on older platforms

### ISSUE THREAD

**Issue by csH7KmCC9** [SRI-CSL/yices2#361]
Please see [this issue in PySMT](https://github.com/pysmt/pysmt/issues/690). PySMT downloads the static yices binaries from the project website. When I try to run those binaries, I get `SIGILL`. Compiling yices from source works fine, though. For context, this is on a Core i7 3000-series processor--old, but not that old.

Is this intended behavior? I know that appealing to the lowest common denominator hurts performance for everyone else. Still, it's a bit of a mysterious and cryptic error for probably a double-digit percentage of your user base.

**Comment by BrunoDutertre** [comment]
This is a known issue. We link statically with libgmp.a and the libgmp.a
we build uses the AVX2 instructions, which are not supported on old
hardware.

This has been reported several times, but the fix is easy (i.e., build it from source)
and that does not seem to affect too many people.

**Comment by csH7KmCC9** [comment]
OK, I see, no problem. Now that I am looking I see a little blurb about it at the end of FAQ.md but obviously it's not very prominent. Maybe you can add a warning in README.md or on the website near the download link? (i.e. "Binaries: (note: requires AVX2 support)" with "requires AVX2 support"  a link to that blurb in the FAQ)

**Comment by BrunoDutertre** [comment]
That sounds reasonable. We'll update the website.

**Comment by csH7KmCC9** [comment]
Cool. Thanks!
