### ISSUE TITLE
Issues with the tests

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/yices2#367]
So if I configure with:
```
./configure --enable-thread-safety
```
and do a 
```
make
```
or a 
```
make check
```
I see a `-DTHREAD_SAFE` in the command line arguments to the compiler.
But if I do a 
```
make test
```
I don't see it. Subsequently I get errors about 
```
section .tbss mismatches non-TLS reference in ...
```
because of the compilation mismatch.

**Comment by BrunoDutertre** [comment]
I've fixed the Makefiles. Is it working for you now?

**Comment by ianamason** [comment]
Thanks! I’ll check once I power down my effigy VM, and fire up the yices one.

**Comment by ianamason** [comment]
Thanks. Compiles fine now.
