### ISSUE TITLE
Support for Dotnet bindings 

### ISSUE THREAD

**Issue by ptr1120** [SRI-CSL/yices2#373]
Hello,

I am interested in using Yices2 in Dontnet (C#). As I see you already have bindings for various languages. Are there any plans to support the usage of Yices2 in Dotnet?

Best regards
Peter

**Comment by ianamason** [comment]
I don't think we have any in house knowledge about dotnet unfortunately.  My guess is they wouldn't be too hard to write by following along what the Java bindings do. But no expertise means no plans.
