### ISSUE TITLE
The Source Code link is broken

### ISSUE THREAD

**Issue by yurivict** [SRI-CSL/yices2#397]
[Here](https://yices.csl.sri.com/).

**Comment by ianamason** [comment]
We know. GitHub has the source. The yices site is in the process of moving (tectonically) to AWS to get around SRI's central IT censorship. When it moves, I will update the link. Meanwhile you can always click [here](https://github.com/SRI-CSL/yices2/archive/refs/tags/Yices-2.6.4.tar.gz) to get the 2.6.4 source.

**Comment by ianamason** [comment]
I just fixed this @disteph. 

But I don't see you as a user of the AWS box, so you will have to follow up with cisco.
