### ISSUE TITLE
E: Unable to locate package yices2

### ISSUE THREAD

**Issue by abc767234318** [SRI-CSL/yices2#408]
I run the following command in Ubuntu.
```
sudo add-apt-repository ppa:sri-csl/formal-methods
sudo apt-get update
sudo apt-get install yices2
```
but output following:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package yices2
```

**Comment by ianamason** [comment]
What version of Ubuntu?

**Comment by abc767234318** [comment]
> What version of Ubuntu?

```
ubuntu@VM-24-16-ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by ianamason** [comment]
Yes it looks like we didn't do Focal.  I just clicked the appropriate buttons on launchpad, so hopefully the packages
will appear sometime soon. Sorry for the delay.

**Comment by ctark7** [comment]
Hello! I ran into the same issue on a different version of Ubuntu. See below:
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**Comment by ctark7** [comment]
> Yes it looks like we didn't do Focal. I just clicked the appropriate buttons on launchpad, so hopefully the packages will appear sometime soon. Sorry for the delay.

Hello! I ran into the same issue on a newer version of Ubuntu. See below:
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```
