### ISSUE TITLE
fatal: remote end hung up unexpectedly

### ISSUE THREAD

**Issue by shanmukh2607** [SRI-CSL/yices2#423]
Unable to clone this repo in Ubuntu 20 and results in fatal error.

**Comment by ianamason** [comment]
Why it this an issue with yices? Sounds more like an issue with git or GitHub. Can you clone other github repos?

**Comment by shanmukh2607** [comment]
Yes. I am able to clone all other repos. To give more details: I am using multipass on mac. I was able to clone the repo outside but not in multipass. Not sure what the issue is coz I am able to clone all other repos in multipass.

**Comment by ahmed-irfan** [comment]
I believe that is a multipass issue.

 Please check if have you have disconnected your vpn — usually that interferes with multipass.

**Comment by ahmed-irfan** [comment]
@shanmukh2607 are you still facing the issue?

**Comment by ahmed-irfan** [comment]
Reopen this if it is still an issue.
