### ISSUE TITLE
To do: upgrade per-thread-state

### ISSUE THREAD

**Issue by disteph** [SRI-CSL/yices2#454]
...to the latest master.
Then I'd like to propose to make it the new master. It seems that any single-threaded usage of Yices API is a valid use of the per-thread-state API, except that yices_init should become yices_global_init and yices_exit should become yices_global_exit. If no workers threads are involved, it looks like we should get the same behavior as with the single-threaded API.
Am I missing anything?

**Comment by ianamason** [comment]
The main thread will need to do a thread init and thread exit if it wants to do some SAT solving.

**Comment by disteph** [comment]
With the above, call ```yices_global_init();``` if you don't, and ```yices_init();``` if you do.

**Comment by disteph** [comment]
and that's backward compatible with both branches.

**Comment by ianamason** [comment]
One aspect that may require some work, I'm not absolutely sure, but the configure stuff will need work I think.
Since per-thread-state conflicts with thread-safety...

**Comment by ahmed-irfan** [comment]
merged master into the per-thread-state branch. 

Currently the CI is disabled for this branch

**Comment by ahmed-irfan** [comment]
up-to-date 789e1a5b54d78e8c55c804e49c47dd001ff1b895
