### ISSUE TITLE
E: Unable to locate package yices2

### ISSUE THREAD

**Issue by ctark7** [SRI-CSL/yices2#535]
I am currently experiencing the same issue as [#408 ](https://github.com/SRI-CSL/yices2/issues/408). My version of Ubuntu is as follows and appears to be unsupported:
```
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble
```

**Comment by ahmed-irfan** [comment]
Please check now. 
Yices2.6.5 is available
