### ISSUE TITLE
Add .md file extension to /doc directory

### ISSUE THREAD

**Issue by neoneye** [SRI-CSL/yices2#58]
The [doc directory](https://github.com/SRI-CSL/yices2/tree/master/doc) seems to contain markdown formatted documents.

The documents currently has no file extension, so github shows them as plain text. 

Some of them looks to be all markdown. Others looks more complex, so these may be more difficult to make look good.

edit: Or add `.rst` extension. I have seen a few files in the project with this extension.

**Comment by BrunoDutertre** [comment]
Thanks for the suggestion. None of these files were intended to
be markdown or rst, but we may convert them at some point.
Not high priority.
