### ISSUE TITLE
Create an Ubuntu Package

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/yices2#59]
Now that we are open source, we should build Ubuntu packages. 

- Guide for PPA: https://help.launchpad.net/Packaging/PPA
- Building PPAs from Travis: https://docs.travis-ci.com/user/deployment/launchpad/

**Comment by ianamason** [comment]
Want me to do this?

**Comment by ianamason** [comment]
Notes that I will add to during this adventure.

1. I created a SRI-CSL team on launchpad so we can publish any packages there. Currently I am the administrator, but if you send me your Ubuntu one user name I can add you as well.

**Comment by dddejan** [comment]
Cool!

**Comment by ianamason** [comment]
single libpoly and yices packages exist (but are not of the dev, dbg variety) and have lintian warnings. 
(ianamason forks with thousands of commits; will squash into one when ...)

```
W: libpoly source: changelog-should-mention-nmu
W: libpoly source: source-nmu-has-incorrect-version-number 0.1.3-1
W: libpoly: package-name-doesnt-match-sonames libpoly0
W: libpoly: wrong-bug-number-in-closes l3:#XXXXXX
W: libpoly: new-package-should-close-itp-bug
W: libpoly: non-dev-pkg-with-shlib-symlink usr/lib/libpoly.so.0.1.1 usr/lib/libpoly.so
```


```
W: yices2: package-name-doesnt-match-sonames libyices2.6
W: yices2: wrong-bug-number-in-closes l3:#XXXXXX
W: yices2: new-package-should-close-itp-bug
W: yices2: binary-without-manpage usr/bin/yices
W: yices2: binary-without-manpage usr/bin/yices-sat
W: yices2: binary-without-manpage usr/bin/yices-smt
W: yices2: binary-without-manpage usr/bin/yices-smt2
W: yices2: non-dev-pkg-with-shlib-symlink usr/lib/x86_64-linux-gnu/libyices.so.2.6.0 usr/lib/x86_64-linux-gnu/libyices.so
```

**Comment by ianamason** [comment]
@dddejan   the dependencies of libpoly are still way over the top (python-sympy is probably the culprit)

**Comment by dddejan** [comment]
The package for libpoly doesn't need the python interface, just the C library. Packaging the python interface, I presume, is better done in pip. If you can package only the C library then the only runtime dep is gmp, and C/cmake for compile.

I'll add a cmake option to disable python entirely.

**Comment by ianamason** [comment]
sounds good. let me know when it is there and I'll pull it in.

**Comment by dddejan** [comment]
Done

**Comment by ianamason** [comment]
Smooth as silk. 

```
Now running lintian...
W: libpoly: package-name-doesnt-match-sonames libpoly0
W: libpoly: wrong-bug-number-in-closes l3:#XXXXXX
W: libpoly: new-package-should-close-itp-bug
W: libpoly: non-dev-pkg-with-shlib-symlink usr/lib/libpoly.so.0.1.1 usr/lib/libpoly.so
Finished running lintian.
```

**Comment by dddejan** [comment]
What are all these other warnings? Ideally I'd like to get rid of all of them. Like non-dev-pkg-with-shlib-symlink.

**Comment by ianamason** [comment]
I certainly agree with the desire to eliminate all the warnings.  it would also be
nice to produce a -dev and -dbg package. maybe the debian mentoring process
would help here.  i have had no luck producing anything other than these "all-in-one"
packages.

**Comment by ianamason** [comment]
The following works on my 14.04 test machine.

```
sudo add-apt-repository ppa:sri-csl/formal-methods
sudo apt-get update
sudo apt-get install yices-dev
```

Still a few mysteries, like how to publish for 'precise' without going through the whole
rigamarole from scratch (trusty appears in the changelog as the distribution).

**Comment by ianamason** [comment]
So we now have  debs for precise and trusty.

Any others desired? Now would be the time, strike while the iron is hot etc.

Seems like the only safe way is to edit the changelog, repackage, and upload.
Need to bump the debian revision for launchpad not to reject the underlying tarball
as a duplicate (seems odd).

Here are some spells:
```
#only need the source packages to upload to the ppa;
#the binaries get built by launchpad. I was building
#on a debian jessie box, so lintian complains about
#ubuntu distribution names, but you can ignore these.

debuild -S -us -uc

# the F10CFE93 is my gpg key id (you need to register it
# with ubuntu one via its finger print, once you have added your
# ssh keys. very fiddly stuff.
debsign -k F10CFE93 libpoly0_<version>-<debian revision>_source.changes
dput -f csl-ppa libpoly0_<version>-<debian revision>_source.changes

debsign -k F10CFE93 yices2_<version>-<debian revision>_source.changes
dput -f csl-ppa yices2_<version>-<debian revision>_source.changes
```

and here is the contents of my jessie box's `.dput.cf` file:
```
[mentors]
fqdn = mentors.debian.net
incoming = /upload
method = http
allow_unsigned_uploads = 0
progress_indicator = 2
# Allow uploads for UNRELEASED packages
allowed_distributions = .*

[csl-ppa]
fqdn = ppa.launchpad.net
method = ftp
incoming = ~sri-csl/ubuntu/formal-methods/
login = anonymous
allow_unsigned_uploads = 0


```

**Comment by ianamason** [comment]
1. man pages need to be fixed.

2. package names are not great especially libpoly0 (ians opinion) and libyices2-6 and the executables yices2 etc...

`<add to this list>`

**Comment by ianamason** [comment]
Closing this.  Our PPA seems to be sufficient.
