### ISSUE TITLE
Create Homebrew formula

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/yices2#60]
For homebrew-science.

**Comment by ianamason** [comment]
My guess is they don't configure with `--enable-mcsat` since there is no 
homebrew-science formula for libpoly.  I made a comment to this effect on the 
yices 2.5.2 (new formula) #5757 thread. But not sure if it will get a response.

**Comment by Moisan** [comment]
Hi! My plan is to have libpoly accepted in homebrew-science and then do another PR to use `--enable-mcsat`.

**Comment by prashantbarca** [comment]
We need to fix the docs on the ReadMe!

**Comment by ianamason** [comment]
Note that to build libpoly without all the python dependencies (i.e. just the `.so`) use the 
incantation
```
cmake .. -DLIBPOLY_BUILD_PYTHON_API=OFF -DLIBPOLY_BUILD_STATIC=OFF -DLIBPOLY_BUILD_STATIC_PIC=OFF
```

**Comment by ianamason** [comment]
@Moisan what is the process for updating the formula? We have just published
python bindings for yices (`pip install yices`) but it requires the latest yices `2.5.4`
so we need to do a version bump.  

Also the libpoly adventure seems to have stalled. Is there anyway we can rekindle the process?

**Comment by ianamason** [comment]
OK we now have our own tap. Thanks for all your help @Moisan !
