### ISSUE TITLE
Yices dumps its guts in global name space / breaks curses

### ISSUE THREAD

**Issue by StevenEker** [SRI-CSL/yices2#67]
Thousands of internal symbols that don't begin with yices_ have global visibility in libyices.a (Linux and Darwin). In particular yices redefines tputs() from the curses/ncurses library, breaking programs that support line editing on user input.

**Comment by BrunoDutertre** [comment]
This issues affects only people who use the static library. We are not going
to add a yices_ prefix to all the function names when these functions are not
part of the API.

**Comment by dddejan** [comment]
Just as reference.

https://stackoverflow.com/questions/393980/restricting-symbols-in-a-linux-static-library

**Comment by StevenEker** [comment]
On Friday, June 23, 2017 04:48:01 PM Dejan Jovanović wrote:
> Just as reference.
> 
> https://stackoverflow.com/questions/393980/restricting-symbols-in-a-linux-st
> atic-library

I'm using objcopy to make the offending symbol local on Linux. This fail under 
Mac OS X, because ld groks Mach symbols but won't produce .a files, and 
ar/libtool/ranlib make .a files but won't mess with Mach symbols.

**Comment by BrunoDutertre** [comment]
Try to put  libyices.a last on your link command.

**Comment by BrunoDutertre** [comment]
No more complaints  on this from Steven Eker.  I assume it's fixed.
