### ISSUE TITLE
GPL with linking exception or LGPL

### ISSUE THREAD

**Issue by maelvalais** [SRI-CSL/yices2#77]
Dear Yices2 team,

Let me first thank you for your excellent work; the idea to move to the GPL was a great move!!

The educationnal-purposed tool I am working on is MIT licensed (https://github.com/touist/touist) which means it is incompatible with the standard GPL, even though I am just linking to `yices.a/so`.

What do you think about adding a linking exception to the GPL license? Or LGPL licensing (like GMP)? I could also choose to move from the MIT to the GPLv3 license, but I don't really think the TouIST project has so much value and should be restricted to the open source community. Another licensing dilemma!

Best regards,

Maël

**Comment by pjljvandelaar** [comment]
Unfortunately, the definition of linking is unclear.
See e.g. https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

Could you make clear what Yices considers linking?

For me personally, I would like to know whether 
* a command line call by another program is already considered as linking?
* mentioning yices and the parameters a tool wants to pass in a configuration file is already considered as linking?

**Comment by BrunoDutertre** [comment]
SRI has no plan to change or alter its license.
