### ISSUE TITLE
Version bump needed.

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/yices2#79]
Executive summary: need to bump yices up to  2.5.4

Why:
So yesterday I could not use the new python bindings with the PPA version because
it was out of date. Specifically it did not have the API additions we made August 30 (the _fd stuff).
This resulted in the pip install bombing because of missing symbols.

So I will need to upload new packages today. I will also see if I can do it for both xenial and precise. (16.04 and 14.04). Which requires some naming tricks I think.

@dddejan  has libpoly changed?  Did we make any progress on the debian stuff?

@BrunoDutertre  have we created a changelog somewhere where we can keep a record of this stuff?

**Comment by dddejan** [comment]
Unfortunately no progress on debian.

**Comment by BrunoDutertre** [comment]
No changelog. Git commit messages are the best we have.

**Comment by ianamason** [comment]
Closed by 2a90fceb57a643286dde8804154b06611f7f3f31
