### ISSUE TITLE
incomplete model returned by yices_smt2

### ISSUE THREAD

**Issue by bsorav** [SRI-CSL/yices2#82]
`$ yices_smt2 --version`
Yices 2.5.4
Copyright SRI International.
Linked with GMP 5.1.3
Copyright Free Software Foundation, Inc.
Build date: 2017-10-29
Platform: x86_64-pc-linux-gnu (release)

`$ cat a.smt2`
; benchmark
(set-info :status unknown)
(set-logic QF_AUFBV)
(declare-fun y () (Array (_ BitVec 1) (_ BitVec 2)))
(declare-fun x () Bool)
(assert
(not (= x (= ((_ extract 0 0) (select y (_ bv0 1))) (_ bv1 1)))))
(check-sat)
(get-model)

`$ yices_smt2 a.smt2`
sat
(= x true)

**Issue : A binding for 'y' is not returned in the model.  This seems incorrect as there exist bindings of 'y' that can make this formula unsatisfiable (for x = true).**

(I have deliberately minimized the example to reproduce the issue.  The same issue occurs for larger arrays.).

**Comment by BrunoDutertre** [comment]
The functions that print a model are missing some relevant variables.

**Comment by bsorav** [comment]
After some more hit-and-trial experiments with the output model, I find that yices seems to be assuming "default" values for missing variables.

The default values are:
- 0 for bitvectors, arrays and functions
- true for booleans

It will be great if you could please confirm this behaviour. Thank you.

**Comment by dddejan** [comment]
I just noticed the same problem with MCSAT and QF_NRA.

**Comment by BrunoDutertre** [comment]
@bsorav,  It's true that there's a default value for each type and that's how
the model is constructed. But the default for Booleans is false not true.

In your example, you have the constraint of the form
```
(not (= x (.. y...)))
```
That simplifies to `(= x (not (... y ...)))` then x is eliminated by substitution.
When the model is constructed, array y is given the default value for bitvector 
arrays, then the value of x is computed from that.

**Comment by bsorav** [comment]
Thanks @BrunoDutertre for the clarification.

This type of "elimination" would require more work from anybody who is looking to (programmatically) read the model.  This elimination logic assumes that the consumer of the model can perform sophisticated reasoning (similar to what Yices does internally).

I would imagine that it would be easier for Yices developers to emit bindings for all defined variables/functions, and harder for a Yices client to infer these bindings. Curious to hear your thoughts.

Thanks.

**Comment by ianamason** [comment]
@bsorav do not misinterpret what is (not)  being said, it is definitely a bug that the values are missing and will be fixed shortly.

**Comment by BrunoDutertre** [comment]
@bsorav: this should be fixed now. Try it.
