### ISSUE TITLE
logic ALL not known

### ISSUE THREAD

**Issue by pjljvandelaar** [SRI-CSL/yices2#84]
the smt2 snippet
```
(get-info :name)
(get-info :version)
(set-logic ALL)
```
yields
```
(:name "Yices")
(:version "2.5.4")
(error "unknown logic: ALL")
(error "no logic set")
```
However, since smtlib 2.5 (see e.g. http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.5-draft-2.pdf section 1.1.1 `Differences between Version 2.5 and Version 2.0`) it is stated: 
```
There is now a predeﬁned argument, ALL, for the set-logic command which refers to the most general logic supported by the solver executing the command.
```

Could you please add the recognition of `ALL`?

**Comment by BrunoDutertre** [comment]
OK, I'll add support for this, even though this is a terrible idea in my opinion.
There's no "most general logic" supported by Yices 2, so ALL will be the
same as QF_BVAUFLIRA.

Bruno

**Comment by pjljvandelaar** [comment]
Thanks

**Comment by pjljvandelaar** [comment]
Any idea when update is incorporated in (released/development) version?

**Comment by BrunoDutertre** [comment]
I'm planning a new release by the end of the month.
It should include this extension, bug fixes, and a few
other improvements.

**Comment by BrunoDutertre** [comment]
Done as part of better support for SMT-LIB 2.5.

**Comment by pjljvandelaar** [comment]
When is the next release of yices plannef that contains this  change?

**Comment by ianamason** [comment]
After the SMT competition probably.
