### ISSUE TITLE
Yices crashes while reporting error

### ISSUE THREAD

**Issue by pjljvandelaar** [SRI-CSL/yices2#85]
When I run 
```
yices-smt2 example.txt
```
on `Microsoft Windows [Version 6.1.7601]`
where `example.txt` equals
```
(declare-fun $In$1012$0$1$() Int)
(get-info :name)
(get-info :version)
```
See also attached file: [example.txt](https://github.com/SRI-CSL/yices2/files/1840527/example.txt)

Yices crashes and I only get
```
(error "at line 1, column 30: undefined sort: Int")
```
I am missing the output that I get when I out comment the first line:
```
(:name "Yices")
(:version "2.5.4")
```

Additional info:
```
C:\>yices-smt2 --version
Yices 2.5.4
Copyright SRI International.
Linked with GMP 6.1.2
Copyright Free Software Foundation, Inc.
Build date: 2017-10-16
Platform: x86_64-pc-mingw32 (release/static)
```

**Comment by BrunoDutertre** [comment]
This is the expected behavior. Yices exits on the first error.
I tried on Windows, Linux, and Mac. I didn't see a crash.
If it crashes for you, then please provide more details.

**Comment by pjljvandelaar** [comment]
I did see multiple errors before exit.
See e.g. my previous bug report where I observed '(error "unknown logic: ALL")
(error "no logic set")'

I did not expect an error on exit. Yet if that is required, I should close this issue.
