### ISSUE TITLE
Support for extended assert?

### ISSUE THREAD

**Issue by varunpatro** [SRI-CSL/yices2#88]
Hello,

Yices 1 has support for max sat through the use of `assert+` commands.

May I ask if Yices 2 has support for it as well? Does Yices 2 support weighted assert in any form?

Thanks,
Varun

**Comment by BrunoDutertre** [comment]
Yices 2 does not support weighted maxsat and it is not in our plans to 
support it. We are planning to add Unsat cores to Yices, which gives
a way to implement known maxsat algorithms.

Bruno
