### ISSUE TITLE
Asserting obviously false produces spurious `unsat`

### ISSUE THREAD

**Issue by yav** [SRI-CSL/yices2#91]
When using `yices`, asserting "obviously" false things like `(assert false)` results in a spurious `unsat` being printed out, before the `(check)` command is issued.   It would be nicer, if the solver's responses matched the queries issued by the user. 

Also, after the false assertion is issued, the solver enters "unsat" mode, and won't allow certain commands (e.g., `push`).

All of this makes it harder to interact with the solver from other programs.

**Comment by BrunoDutertre** [comment]
That's a matter of choice. It is useful to know that something is unsat as soon as possible.
If you want to use Yices interactively, then you can use the SMT-LIB 2 front end, which
works like you want.  But, in my opinion, the best way to do things interactively is to use 
the API, or the python bindings, or issue the commands one by one and parse the result.

**Comment by robdockins** [comment]
Is there an option to make the Yices native frontend send an acknowledgment after successful commands (like the SMTLib2 `success` result)?  I don't see one in the manual.  If not, we can't reliably look for the `unsat` message.

**Comment by BrunoDutertre** [comment]
I'll add a flag for that. Right now, you get an "ok" if you run yices with --verbosity=1 (or more)
and the input is from a terminal.

**Comment by BrunoDutertre** [comment]
Just added a command-line option --print-success that forces yices to
print 'ok' after every command (except the ones that already print 
something). Hope that works for @robdockins.

**Comment by robdockins** [comment]
It would be a lot better if the "ok" and "unsat" messages were printed on `stdout` rather than `stderr`.

**Comment by BrunoDutertre** [comment]
What about the error messages? Should they go to stdout too?

**Comment by robdockins** [comment]
For us, the useful distinction is that machine-readable messages that are necessary to keep our process in sync with the solver are should be on stdout, and anything else is better on stderr.  So user-readable error messages are better on stderr.

**Comment by BrunoDutertre** [comment]
Done in 10a935c5

**Comment by robdockins** [comment]
With the `--print-success` flag we can now properly parse responses to commands, and thus catch it when assert commands respond with `unsat`, so I think we can close this bug.
