### ISSUE TITLE
Install doesn't link through libyices.so.2.6

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/yices2#93]
I don't know why, but install only links straight

libyices.so -> libyices.so.2.6.0

I'm not an expert but my understanding is that the links should go 

libyices.so -> libyices.so.2.6 -> libyices2.6.0

This breaks programs using the library (e.g., sally).

**Comment by dddejan** [comment]
The issue with sally is that it links against 2.6 and not just yices (this is required for new features),

**Comment by dddejan** [comment]
Changing install in Makefile.build fixes this:

```
install-linux install-unix: install-default
	$(LDCONFIG) -n $(DESTDIR)$(libdir) && (cd $(DESTDIR)$(libdir) && $(LN_S) -f libyices.so.$(YICES_VERSION) libyices.so.$(MAJOR).$(MINOR) && $(LN_S) -f libyices.so.$(MAJOR).$(MINOR) libyices.so)
```
I'm not an expert, is this the thing to do?

**Comment by BrunoDutertre** [comment]
ldconfig is supposed to create the link. libiyces.so.2.6 -> libyices.so.2.6.0.

That's what happens on my Linux box:
```
lrwxrwxrwx 1 root root       17 Jul 10 10:59 /usr/local/lib/libyices.so -> libyices.so.2.6.0*
lrwxrwxrwx 1 root root       17 Jul 10 10:59 /usr/local/lib/libyices.so.2.6 -> libyices.so.2.6.0*
-rwxr-xr-x 1 root root  1920568 Jul 10 10:59 /usr/local/lib/libyices.so.2.6.0*
```

**Comment by dddejan** [comment]
Ok. I'll check what's going on but this was not happening on my computer or the docker I'm trying to build.

So why is there manual linking in the makefile?

**Comment by BrunoDutertre** [comment]
ldconfig does not create the link libyices.so -> libyices.so.2.6.0.
But libyices.so is needed to compile/link with -lyices.

**Comment by dddejan** [comment]
Ok, I'm starting to see how it's supposed to work.

I've checked again the linux box, and it seems to work fine actually. So the problem seems to be the ldconfig used in the alpine linux that I'm using for docker . I looked into it and their version of ldconfig is a stupid hacked script that ignores standard lib directories. Don't know why, but that's what it does.
