### ISSUE TITLE
Bug and/or unhelpful error message in nonlinear solver

### ISSUE THREAD

**Issue by robdockins** [SRI-CSL/yices2#95]
The following file, when processed via `yices` (recent head, rev 4aeef3a28f4c1be8d2d1c8c33a23048b8f4434e0) without setting a specific logic, will accept the file and find a satisfying model.  When run with `--logic=QF_NIRA`, it prints a totally unhelpful error message.

```
(define x::real)
(define x!9::(bitvector 32))
(define x!6::int (if (= (bv-extract 0 0 x!9) (mk-bv 1 1)) 1 0))
(assert (< x x!6))
(check)
(show-model)
```

```
$ yices bug.yices
sat
(= x -1)
(= x!9 0b00000000000000000000000000000000)

$ yices --logic=QF_NIRA bug.yices
bug.yices: (null) (line 4, column 19)
```

I guess maybe the combination of reals, integers and bitvectors is no supported?

**Comment by robdockins** [comment]
Thanks @BrunoDutertre.  What's the prognosis for the bitvector theory in mcsat?

**Comment by BrunoDutertre** [comment]
We're working on it. Not clear how long that will take.
