### ISSUE TITLE
Python binding installation failure when Yices is installed locally

### ISSUE THREAD

**Issue by shaobo-he** [SRI-CSL/yices2#96]
Hey Yices developers,

When I installed Yices locally (using `./configure --prefix=...`), `pip install yices` fails with the following error message,

```
Collecting yices
  Using cached https://files.pythonhosted.org/packages/92/44/0a4cc730d292bad67eed2606b6cb07b7fd4a7ec11d3445af84893ed3286c/yices-1.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-J6xIUk/yices/setup.py", line 17, in <module>
        from yices import yices_python_version
      File "yices.py", line 220, in <module>
        loadYices()
      File "yices.py", line 216, in loadYices
        raise YicesException(error_msg)
    yices.YicesException: Yices dynamic library not found.
    
    ----------------------------------------
```

It seems `yices.py` uses `find_library` of Python's `ctypes.util` module, which seems to only search for system library path. I tried to set the `LD_LIBRARY_PATH` environment variable but it didn't work either.

Btw, I'm using Ubuntu 14.04.

**Comment by ianamason** [comment]
Thanks for the heads up. We will come up with a solution soon.

**Comment by dddejan** [comment]
Maybe best to push the loading of library to init_yices() with an optional parameter being the location of the library?

**Comment by ianamason** [comment]
Is that really necessary? CDLL seems to do the job properly. The only bad apple in the mix is
find_library. Maybe we should just remove find_library.

**Comment by dddejan** [comment]
Yeah, not necessary if LD_LIBRARY_PATH works :) 
It might be easier on the user.

**Comment by kgoyal40** [comment]
Hi, I tried it with setting the LD_LIBRARY_PATH to the yices library. I still get the same issue. Is there any other fix for this?

**Comment by ianamason** [comment]
If you @kgoyal40  provide more details of your setup I may get time to investigate.

**Comment by kgoyal40** [comment]
well, I tried to install the python API of yices using pip, I got the error:

yices_api.YicesAPIException: Yices dynamic library not found.

Then i tried manually adding the yices source as LD_LIBRARY_PATH, still the same issue when i run the setup script.

**Comment by ianamason** [comment]
Operating system? Distribution?
Did you try installing the bindings from source?

**Comment by kgoyal40** [comment]
I'm using the ubuntu 18.04. python 3.7.1.

I'm not sure how to install the bindings from the source. Is there a documentation for that? I first tried using pip and then by cloning the repository and using the setup.py after changing the path variable.

**Comment by ianamason** [comment]
[here](https://github.com/SRI-CSL/yices2_python_bindings)

**Comment by kgoyal40** [comment]
Yes, I used the "pip install yices" as it mentions in the documentation.

**Comment by kgoyal40** [comment]
Yes, I installed the yices SMT solver and then the python binding which gave the following error:

 CDLL(libyices.so) raised libyices.so: cannot open shared object file: No such file or directory.
    
    CDLL(/usr/local/lib/libyices.so) raised /usr/local/lib/libyices.so: cannot open shared object file: No such file or directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yoqbv0ab/yices/setup.py", line 17, in <module>
        from yices_api import yices_python_version
      File "/tmp/pip-install-yoqbv0ab/yices/yices_api.py", line 229, in <module>
        loadYices()
      File "/tmp/pip-install-yoqbv0ab/yices/yices_api.py", line 225, in loadYices
        raise YicesAPIException(error_msg)
    yices_api.YicesAPIException: Yices dynamic library not found.

**Comment by ianamason** [comment]
Yes but I am not sure the pip package is upto date.
I am busy with another project, so won’t get to this any time soon.

**Comment by kgoyal40** [comment]
is there any other way to install the python bindings?

**Comment by BrunoDutertre** [comment]
It looks like python is complaining that /usr/local/lib/libyices.so is not found.
Can you check that this file exists on your system?

**Comment by kgoyal40** [comment]
Actually no. It should've been created when I installed the yices sovler but didn't. Do you have any idea why?

**Comment by BrunoDutertre** [comment]
How did you install Yices?

**Comment by kgoyal40** [comment]
I used the following commands as mentioned on the website
sudo add-apt-repository ppa:sri-csl/formal-methods
sudo apt-get update
sudo apt-get install yices2

**Comment by BrunoDutertre** [comment]
You probably have to do this too:
```
sudo apt-get install libyices2
```

**Comment by ianamason** [comment]
The readme says:
```
sudo apt-get install yices2-dev
```

**Comment by kgoyal40** [comment]
One unrelated question, how can I use the soft assertions (MAXSMT) using the yices python api?

**Comment by ianamason** [comment]
yices does not support MAXSMT natively.

You could do it yourself using unsat cores.
