### ISSUE TITLE
check-sat-assuming returns SAT for UNSAT QF_NRA problem

### ISSUE THREAD

**Issue by daniel-larraz** [SRI-CSL/yices2#97]
You can find [attached](https://github.com/SRI-CSL/yices2/files/2299677/bmc_check_sat_assuming.zip) two versions of the same problem:

bmc_sat.smt2 uses check-sat-assuming, yices-smt2 returns SAT

bmc_unsat.smt2 uses check-sat, yices-smt2 returns UNSAT

**Comment by BrunoDutertre** [comment]
unsat-cores and check with assumptions are not supported in QF_NRA.
I've fixed the code to check for this and print an error.
