### ISSUE TITLE
Illegal instruction (core dumped) on assert commands

### ISSUE THREAD

**Issue by MarcRoigVilamala** [SRI-CSL/yices2#98]
I have found a very strange error in yices-smt2, version 2.6.0.

I have tried to execute the following code:

```smt2
(set-logic QF_LIA)
(declare-const x Int)
(assert (< x 1))
(check-sat)
(get-value (x))
(exit)
```

And it returns the error:

```
Illegal instruction (core dumped)
```

It seems to be caused by the instruction `(assert (< x 1))`. However, very strangely, the error does not happen if the constant is 0. The following code:

```smt2
(set-logic QF_LIA)
(declare-const x Int)
(assert (< x 0))
(check-sat)
(get-value (x))
(exit)
```

Returns

```
sat
((x (- 1)))
```

I have tested with different values for the constant and only 0 seems to work.

I have also checked if this works on different computers. In both my personal computer (Windows 10) and another computer (Fedora 27) this error does not happen. 

However, for a server (Fedora 28) this does happen.

Finally, the weirdest case is in a server in which the code works if I try it directly (with the instruction `yices-smt2 foo.smt2`). However, if I use it inside a `qsub` command it does not and returns the same error.

All the installations were done by using the download link from http://yices.csl.sri.com/ using the Linux 64 bit option (except for the Windows 10, for which I used the Windows 64 option).

I have used the 2.4.2 version of Yices and it works everywhere. Versions 2.5.x do not work either, so it would seem that the error was introduced between the 2.4.2 and 2.5 versions.

**Comment by BrunoDutertre** [comment]
@MarcRoigVilamala: It's most likely a hardware incompatibility, related to a new
version of GMP we link yices with. Can you try this:
```
 grep avx2 /proc/cpuinfo
```
on your Linux machines? If you see nothing, then your CPU
does not have the AVX2 instructions and that would cause
the illegal instruction error.

If that's the case, you can fix the problem by building Yices
from the source on your machine.

**Comment by MarcRoigVilamala** [comment]
Thank you, that seems to be the case.
